import { defineConfig } from "orval";

export default defineConfig({
	cluster: {
		input: {
			target: "./.orval/cluster.openapi.yaml",
		},
		output: {
			target: "./src/api/generated/cluster.ts",
			schemas: false,
			client: "fetch",
			mode: "single",
			baseUrl: "/api/v1",
			clean: true,
			tsconfig: "./tsconfig.app.json",
			override: {
				header: () => [
					"Generated by Orval from docs/contracts/api/w1-1.openapi.yaml.",
					"Do not edit this file directly; run npm run api:generate.",
				],
			},
		},
		hooks: {
			afterAllFilesWrite: "prettier --write ./src/api/generated",
		},
	},
	w12: {
		input: {
			target: "./.orval/cluster-w1-2.openapi.yaml",
		},
		output: {
			target: "./src/api/generated/w1-2.ts",
			schemas: false,
			client: "fetch",
			mode: "single",
			baseUrl: "/api/v1",
			clean: false,
			tsconfig: "./tsconfig.app.json",
			override: {
				header: () => [
					"Generated by Orval from docs/contracts/api/w1-2.openapi.yaml.",
					"Do not edit this file directly; run npm run api:generate.",
				],
			},
		},
		hooks: {
			afterAllFilesWrite: "prettier --write ./src/api/generated",
		},
	},
});
