import { defineConfig } from "orval";

export default defineConfig({
	cluster: {
		input: {
			target: "../../docs/contracts/api/openapi.yaml",
		},
		output: {
			target: "./src/api/generated/cluster.ts",
			schemas: false,
			client: "fetch",
			mode: "single",
			baseUrl: "/api/v1",
			urlEncodeParameters: true,
			clean: true,
			tsconfig: "./tsconfig.app.json",
			override: {
				mutator: {
					path: "./src/api/fetcher.ts",
					name: "customFetch",
				},
				header: () => [
					"Generated by Orval from docs/contracts/api/openapi.yaml.",
					"Do not edit this file directly; run npm run api:generate.",
				],
			},
		},
		hooks: {
			afterAllFilesWrite: "prettier --write ./src/api/generated",
		},
	},
});
