import type { Locale } from '../../i18n'

export type Copy = Record<Locale, string>

export function t(copy: Copy, locale: Locale): string {
  return copy[locale]
}

export const platformCopy = {
  title: { ar: 'إدارة المنصة', en: 'Platform Management' },
  description: {
    ar: 'مراقبة تشغيل المنصة وإعداداتها وصيانتها',
    en: 'Monitor platform operations, settings, and maintenance',
  },
  tabs: {
    overview: { ar: 'نظرة عامة', en: 'Overview' },
    security: { ar: 'إعدادات الأمان', en: 'Security settings' },
    calendars: { ar: 'التقويمات', en: 'Business calendars' },
    backups: { ar: 'النسخ الاحتياطي', en: 'Backups' },
    logs: { ar: 'السجلات الفنية', en: 'Technical logs' },
    health: { ar: 'الصحة', en: 'Health' },
    maintenance: { ar: 'الصيانة', en: 'Maintenance' },
  },
  unavailable: { ar: 'غير متاح', en: 'Unavailable' },
  unavailableBody: {
    ar: 'لا تملك صلاحية الوصول إلى هذا القسم.',
    en: 'You do not have access to this section.',
  },
  retry: { ar: 'إعادة المحاولة', en: 'Retry' },
  loading: { ar: 'جارٍ التحميل…', en: 'Loading…' },
  empty: { ar: 'لا توجد بيانات.', en: 'No data.' },
  error: { ar: 'تعذر تحميل البيانات. أعد المحاولة.', en: 'The data could not be loaded. Try again.' },
  forbidden: { ar: 'غير مصرح', en: 'Forbidden' },
  actions: { ar: 'الإجراءات', en: 'Actions' },
  close: { ar: 'إغلاق', en: 'Close' },
  cancel: { ar: 'إلغاء', en: 'Cancel' },
  save: { ar: 'حفظ', en: 'Save' },
  submit: { ar: 'إرسال', en: 'Submit' },
  confirm: { ar: 'تأكيد', en: 'Confirm' },
  refreshed: { ar: 'تم تحديث البيانات.', en: 'Data refreshed.' },
}

export const overviewCopy = {
  status: { ar: 'حالة المنصة', en: 'Platform status' },
  healthy: { ar: 'سليمة', en: 'Healthy' },
  degraded: { ar: 'متراجعة', en: 'Degraded' },
  critical: { ar: 'حرجة', en: 'Critical' },
  unknown: { ar: 'غير معروفة', en: 'Unknown' },
  updatedAt: { ar: 'آخر تحديث', en: 'Last updated' },
  issues: { ar: 'المشكلات', en: 'Issues' },
  noIssues: { ar: 'لا توجد مشكلات معلقة', en: 'No outstanding issues' },
  healthChecks: { ar: 'فحوصات الصحة', en: 'Health checks' },
  checksCount: { ar: 'عدد الفحوصات', en: 'Checks' },
  backupStatus: { ar: 'حالة النسخ الاحتياطي', en: 'Backup status' },
  lastBackup: { ar: 'آخر نسخة ناجحة', en: 'Last successful backup' },
  lastFailed: { ar: 'آخر فشل', en: 'Last failure' },
  runBackup: { ar: 'تشغيل نسخة احتياطية', en: 'Run backup' },
  backupRequested: {
    ar: 'تم إرسال طلب النسخة الاحتياطية. تُحدَّث الحالة عند اكتمال العملية.',
    en: 'Backup requested. Status updates once the operation completes.',
  },
  sourceHealth: { ar: 'الصحة', en: 'Health' },
  sourceBackups: { ar: 'النسخ الاحتياطي', en: 'Backups' },
} as const satisfies Record<string, Copy>

export const securityCopy = {
  policy: { ar: 'سياسة الأمان الحالية', en: 'Current security policy' },
  published: { ar: 'منشورة', en: 'Published' },
  draft: { ar: 'مسودة', en: 'Draft' },
  validated: { ar: 'مُتحقَّق منها', en: 'Validated' },
  retired: { ar: 'متقاعدة', en: 'Retired' },
  noPublished: { ar: 'لا توجد نسخة منشورة بعد', en: 'No published version yet' },
  version: { ar: 'النسخة', en: 'Version' },
  defaultLocale: { ar: 'اللغة الافتراضية', en: 'Default locale' },
  timezone: { ar: 'المنطقة الزمنية', en: 'Timezone' },
  activeLogMonths: { ar: 'أشهر السجل النشط', en: 'Active log months' },
  idleTimeoutMinutes: { ar: 'مهلة الخمول (دقيقة)', en: 'Idle timeout (minutes)' },
  absoluteSessionHours: { ar: 'مدة الجلسة القصوى (ساعة)', en: 'Max session (hours)' },
  minimumPasswordLength: { ar: 'الحد الأدنى لطول كلمة المرور', en: 'Minimum password length' },
  passwordHistoryCount: { ar: 'عدد كلمات المرور السابقة', en: 'Password history count' },
  failedLoginAttempts: { ar: 'محاولات الدخول الفاشلة', en: 'Failed login attempts' },
  failedLoginWindowMinutes: { ar: 'نافذة الفشل (دقيقة)', en: 'Failure window (minutes)' },
  lockoutMinutes: { ar: 'مدة الإقفال (دقيقة)', en: 'Lockout (minutes)' },
  createDraft: { ar: 'إنشاء مسودة جديدة', en: 'Create draft' },
  edit: { ar: 'تعديل القيم', en: 'Edit values' },
  validate: { ar: 'تحقق من الصلاحية', en: 'Validate' },
  publish: { ar: 'نشر', en: 'Publish' },
  versions: { ar: 'إصدارات الإعدادات', en: 'Settings versions' },
  stale: {
    ar: 'تعارض في النسخة: تم تعديل الإعدادات من جهة أخرى. أعيد التحميل.',
    en: 'Version conflict: the settings changed elsewhere. Reloaded.',
  },
  editing: { ar: 'تعديل: ', en: 'Editing: ' },
} as const satisfies Record<string, Copy>

export const calendarsCopy = {
  title: { ar: 'التقويمات', en: 'Business calendars' },
  empty: { ar: 'لا توجد تقويمات بعد.', en: 'No business calendars yet.' },
  create: { ar: 'إنشاء تقويم', en: 'Create calendar' },
  scopeType: { ar: 'نوع النطاق', en: 'Scope type' },
  scopeId: { ar: 'معرّف النطاق', en: 'Scope ID' },
  scopePlatform: { ar: 'المنصة', en: 'Platform' },
  scopeCluster: { ar: 'التجمع', en: 'Cluster' },
  scopeFacility: { ar: 'المنشأة', en: 'Facility' },
  timezone: { ar: 'المنطقة الزمنية', en: 'Timezone' },
  workingDays: { ar: 'أيام العمل', en: 'Working days' },
  weekends: { ar: 'عطل نهاية الأسبوع', en: 'Weekends' },
  holidays: { ar: 'الإجازات', en: 'Holidays' },
  weekday: { ar: 'اليوم', en: 'Day' },
  exception: { ar: 'استثناء', en: 'Exception' },
  editWeekday: { ar: 'تعديل يوم عمل', en: 'Edit weekday' },
  editException: { ar: 'تعديل استثناء', en: 'Edit exception' },
  addException: { ar: 'إضافة استثناء', en: 'Add exception' },
  isWorkingDay: { ar: 'يوم عمل', en: 'Working day' },
  startsAt: { ar: 'بداية', en: 'Starts at' },
  endsAt: { ar: 'نهاية', en: 'Ends at' },
  endsOn: { ar: 'حتى', en: 'Ends on' },
  date: { ar: 'التاريخ', en: 'Date' },
  type: { ar: 'النوع', en: 'Type' },
  reason: { ar: 'السبب', en: 'Reason' },
  publish: { ar: 'نشر', en: 'Publish' },
  days: [
    { ar: 'الأحد', en: 'Sunday' },
    { ar: 'الاثنين', en: 'Monday' },
    { ar: 'الثلاثاء', en: 'Tuesday' },
    { ar: 'الأربعاء', en: 'Wednesday' },
    { ar: 'الخميس', en: 'Thursday' },
    { ar: 'الجمعة', en: 'Friday' },
    { ar: 'السبت', en: 'Saturday' },
  ] as const,
  exceptionTypes: {
    official_holiday: { ar: 'إجازة رسمية', en: 'Official holiday' },
    local_closure: { ar: 'إغلاق محلي', en: 'Local closure' },
    local_hours: { ar: 'دوام محلي', en: 'Local hours' },
    official_holiday_work_override: { ar: 'عمل في إجازة رسمية', en: 'Official holiday work override' },
    ramadan: { ar: 'رمضان', en: 'Ramadan' },
  },
} as const

export const backupsCopy = {
  status: { ar: 'حالة النسخ الاحتياطي', en: 'Backup status' },
  runBackup: { ar: 'تشغيل نسخة احتياطية', en: 'Run backup' },
  requested: { ar: 'مطلوب', en: 'Requested' },
  lastSuccessful: { ar: 'آخر نسخة ناجحة', en: 'Last successful backup' },
  lastFailed: { ar: 'آخر فشل', en: 'Last failure' },
  lastValidation: { ar: 'آخر تحقق', en: 'Last validation' },
  restore: { ar: 'طلب استعادة', en: 'Request restore' },
  backupId: { ar: 'معرّف النسخة', en: 'Backup ID' },
  reason: { ar: 'السبب', en: 'Reason' },
  reasonHelp: { ar: 'اكتب سببًا واضحًا (10 أحرف على الأقل)', en: 'Provide a clear reason (at least 10 characters)' },
  restoreSubmitted: { ar: 'طلب الاستعادة قيد الانتظار', en: 'Restore request submitted' },
  confirmRestore: { ar: 'تأكيد الاستعادة', en: 'Confirm restore' },
  confirmHint: {
    ar: 'تتطلب الاستعادة موافقة مستخدم مختلف عن مقدم الطلب (مبدأ الفاعل الثاني).',
    en: 'Restores require confirmation by a different user than the requester (two-actor rule).',
  },
  confirmed: { ar: 'تم تأكيد طلب الاستعادة', en: 'Restore confirmed' },
  empty: { ar: 'لا توجد بيانات نسخ احتياطي.', en: 'No backup data.' },
} as const satisfies Record<string, Copy>

export const logsCopy = {
  title: { ar: 'السجلات الفنية', en: 'Technical logs' },
  source: { ar: 'المصدر', en: 'Source' },
  category: { ar: 'الفئة', en: 'Category' },
  severity: { ar: 'الخطورة', en: 'Severity' },
  occurredAt: { ar: 'الوقت', en: 'Occurred at' },
  message: { ar: 'الرسالة', en: 'Message' },
  allCategories: { ar: 'كل الفئات', en: 'All categories' },
  allSeverities: { ar: 'كل الخطورة', en: 'All severities' },
  restore: { ar: 'طلب استعادة السجلات', en: 'Request logs restore' },
  manifestId: { ar: 'معرّف الحزمة (Manifest)', en: 'Manifest ID' },
  reason: { ar: 'السبب', en: 'Reason' },
  restored: { ar: 'تم إرسال طلب استعادة السجلات.', en: 'Logs restore requested.' },
  empty: { ar: 'لا توجد سجلات.', en: 'No log entries.' },
  severities: {
    critical: { ar: 'حرج', en: 'Critical' },
    error: { ar: 'خطأ', en: 'Error' },
    warning: { ar: 'تحذير', en: 'Warning' },
    info: { ar: 'معلومات', en: 'Info' },
  } as const,
} as const

export const healthCopy = {
  checks: { ar: 'فحوصات الصحة', en: 'Health checks' },
  code: { ar: 'الفحص', en: 'Check' },
  latency: { ar: 'زمن الاستجابة', en: 'Latency' },
  checkedAt: { ar: 'وقت الفحص', en: 'Checked at' },
  alertPolicies: { ar: 'سياسات التنبيه', en: 'Alert policies' },
  status: { ar: 'الحالة', en: 'Status' },
  severity: { ar: 'الخطورة', en: 'Severity' },
  channel: { ar: 'القناة', en: 'Channel' },
  edit: { ar: 'تعديل', en: 'Edit' },
  empty: { ar: 'لا توجد سياسات تنبيه.', en: 'No alert policies.' },
} as const satisfies Record<string, Copy>

export const maintenanceCopy = {
  title: { ar: 'نوافذ الصيانة', en: 'Maintenance windows' },
  empty: { ar: 'لا توجد نوافذ صيانة.', en: 'No maintenance windows.' },
  schedule: { ar: 'جدولة نافذة صيانة', en: 'Schedule maintenance window' },
  startsAt: { ar: 'البداية', en: 'Starts at' },
  endsAt: { ar: 'النهاية (اختياري)', en: 'Ends at (optional)' },
  messageAr: { ar: 'الرسالة (عربي)', en: 'Message (Arabic)' },
  messageEn: { ar: 'الرسالة (إنجليزي)', en: 'Message (English)' },
  cancel: { ar: 'إلغاء', en: 'Cancel' },
  cancelled: { ar: 'ملغاة', en: 'Cancelled' },
  scheduled: { ar: 'مجدولة', en: 'Scheduled' },
  active: { ar: 'نشطة', en: 'Active' },
  ended: { ar: 'منتهية', en: 'Ended' },
  window: { ar: 'نافذة صيانة', en: 'Maintenance window' },
} as const satisfies Record<string, Copy>
