export type Locale = 'ar' | 'en'

export const text = {
  ar: {
    platform: 'بوابة العمل المؤسسي',
    switchLanguage: 'English',
    signIn: 'تسجيل الدخول',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    signingIn: 'جارٍ تسجيل الدخول…',
    loginError: 'تعذر تسجيل الدخول. تحقق من بيانات الدخول ثم أعد المحاولة.',
    requiredLogin: 'أكمل الحقول المطلوبة ثم أعد المحاولة.',
    welcomeBack: 'مرحباً بعودتك',
    loginGuidance: 'سجّل الدخول باستخدام حساب المنصة الداخلي.',
    internalAccess: 'دخول مخصص للحسابات الداخلية المعتمدة',
    developmentAccounts: 'حسابات التطوير (بيئة التطوير فقط)',
    usernameRequired: 'اسم المستخدم مطلوب.',
    passwordRequired: 'كلمة المرور مطلوبة.',
    showPassword: 'إظهار كلمة المرور',
    hidePassword: 'إخفاء كلمة المرور',
    enableDarkMode: 'تفعيل الوضع الداكن',
    enableLightMode: 'تفعيل الوضع الفاتح',
    currentFacility: 'نطاق العمل الحالي',
    myRequests: 'طلباتي',
    newRequest: 'طلب جديد',
    organization: 'التنظيم',
    organizationStructure: 'الهيكل والمناصب',
    peopleAssignments: 'الأشخاص والتكليفات',
    temporaryAssignments: 'التكليفات المؤقتة',
    identityAccounts: 'حسابات الهوية',
    administrationNavigation: 'تنقل الإدارة',
    importReview: 'مراجعة الاستيراد',
    roles: 'الأدوار',
    capabilities: 'الصلاحيات',
    roleAssignments: 'إسنادات الأدوار',
    delegations: 'التفويضات',
    supervisoryRelationships: 'العلاقات الإشرافية',
    accessExplanation: 'شرح قرار الوصول',
    authorizationGroup: 'الصلاحيات والوصول',
    workflowGroup: 'سير العمل',
    workflowTasks: 'سير العمل والمهام',
    workDefinitions: 'تعريفات العمل',
    workflowAdmin: 'إدارة المسارات',
    myTasks: 'مهامي',
    searchScreen: 'البحث',
    reportsScreen: 'التقارير',
    apiDocs: 'Swagger UI',
    apiDocsBody: 'استعرض العقود التفاعلية من واجهة Swagger UI المبنية من ملف OpenAPI.',
    notifications: 'الإشعارات',
    profile: 'ملفي',
    personalAccess: 'سياق الوصول الشخصي',
    classificationPolicies: 'سياسات التصنيف',
    fieldAccessTemplates: 'قوالب وصول الحقول',
    closeNotifications: 'إغلاق الإشعارات',
    logout: 'تسجيل الخروج',
    loadingRequests: 'جارٍ تحميل طلباتك…',
    listError: 'تعذر تحميل طلباتك. أعد المحاولة.',
    retry: 'إعادة المحاولة',
    emptyTitle: 'لا توجد طلبات بعد',
    emptyBody: 'أنشئ أول طلب للمنشأة الحالية لبدء المسار.',
    noDescription: 'لا يوجد وصف',
    submitted: 'تم الإرسال',
    requestTitle: 'عنوان الطلب (مطلوب)',
    requestDescription: 'وصف الطلب (مطلوب)',
    titleHelp: 'اكتب عنواناً موجزاً يوضح الغرض من الطلب.',
    descriptionHelp: 'أضف التفاصيل اللازمة لمعالجة الطلب.',
    submit: 'إرسال الطلب',
    submitting: 'جارٍ إرسال الطلب…',
    validationError: 'أكمل الحقول المطلوبة ثم أعد الإرسال.',
    titleRequired: 'عنوان الطلب مطلوب.',
    descriptionRequired: 'وصف الطلب مطلوب.',
    submitError: 'لم يتم حفظ الطلب. تحقق من اتصالك الداخلي ثم أعد المحاولة.',
    success: 'تم إرسال طلبك',
    successBody: 'حُفظ الطلب. سيظهر إشعار داخلي هنا بعد اكتمال المعالجة.',
    backToRequests: 'العودة إلى طلباتي',
    loadingDetail: 'جارٍ تحميل الطلب…',
    detailError: 'تعذر تحميل الطلب. أعد المحاولة.',
    unavailable: 'لا يمكنك فتح هذا الطلب أو لم يعد متاحاً.',
    refreshNotifications: 'تحديث الإشعارات',
    refreshingNotifications: 'جارٍ تحديث الإشعارات…',
    notificationError: 'تعذر تحميل الإشعارات. أعد المحاولة.',
    noNotifications: 'لا توجد إشعارات جديدة',
    read: 'مقروء',
    unread: 'غير مقروء',
    sessionExpired: 'انتهت جلستك. سجّل الدخول للمتابعة.',
    notFound: 'الصفحة غير موجودة',
    notFoundBody: 'تحقق من الرابط أو عد إلى طلباتك.',
    openNavigation: 'فتح القائمة الرئيسية',
    closeNavigation: 'إغلاق القائمة الرئيسية',
    navigationTitle: 'التنقل الرئيسي',
    services: 'الخدمات',
    platformUser: 'مستخدم المنصة',
    internalSystem: 'منصة موحّدة',
    rightsReserved: 'جميع الحقوق محفوظة © 2026',
    organizationName: 'مجمع إرادة والصحة النفسية',
    officeName: 'مكتب إدارة المشاريع والتحول المؤسسي',
    ownerName: 'طارق الوليدي',
    collapseNavigation: 'طي القائمة الجانبية',
    expandNavigation: 'توسيع القائمة الجانبية',
    facilityA: 'المنشأة أ',
    facilityB: 'المنشأة ب',
    dashboardWelcome: 'مرحباً بك',
    dashboardSummary: 'إليك ملخص الطلبات والإشعارات ضمن نطاق المنشأة الحالية.',
    dashboardRange: 'حد العرض: 20 طلباً',
    overview: 'نظرة عامة',
    loadedRequests: 'الطلبات المحمّلة',
    activeRequests: 'طلبات قيد الإجراء',
    completedRequests: 'طلبات مكتملة',
    unreadNotifications: 'غير المقروءة المحمّلة',
    currentPageSource: 'من النتائج المحمّلة',
    loadedNotificationSource: 'من إشعارات المستخدم المحمّلة',
    analytics: 'التحليلات',
    timelineTitle: 'التحليلات الزمنية',
    timelineUnavailableTitle: 'لا تتوفر سلسلة زمنية بعد',
    timelineUnavailableBody: 'ستظهر اتجاهات الطلبات عند نشر مصدر التجميع الزمني المعتمد.',
    statusBreakdown: 'الطلبات حسب الحالة',
    activeStatus: 'قيد الإجراء',
    completedStatus: 'مكتملة',
    otherStatus: 'حالات أخرى',
    noStatusTitle: 'لا توجد حالات لعرضها',
    noStatusBody: 'أنشئ أول طلب لتظهر هنا قراءة موجزة لتوزيع الحالات.',
    recentActivity: 'النشاط المتاح',
    openNotifications: 'عرض الإشعارات',
    noNotificationBody: 'ستظهر هنا أحدث التنبيهات المرتبطة بطلبات المنشأة.',
    noData: 'لا توجد بيانات',
    ltr: 'rtl',
    home: 'الرئيسية',
    processesAndWorkflow: 'الإجراءات وسير العمل',
    organization2: 'الهيكل التنظيمي',
    accountsAndAccess: 'الحسابات والصلاحيات',
    coverage: 'تغطية العمليات',
    apiReference: 'مرجع واجهات API',
    documents: 'المستندات',
    myWork: 'مساحة عملي',
    operations: 'الإدارة والتشغيل',
    productReview: 'مراجعة المنتج',
    enGb: 'ar-SA',
    couldNotMarkTheNotification: 'تعذر تحديد الإشعار كمقروء. أعد المحاولة.',
    saving: 'جارٍ الحفظ…',
    markAsRead: 'تحديد كمقروء',
    couldNotLoadMoreNotifications: 'تعذر تحميل المزيد من التنبيهات.',
    loadingMore: 'جارٍ تحميل المزيد…',
    loadMore: 'تحميل المزيد',
    organizationAndWorkforce: 'الهيكل التنظيمي والقوى العاملة',
    requestActions: 'إجراءات الطلب',
    submit2: 'إرسال',
    return: 'إعادة',
    complete: 'إكمال',
    linkedDocuments: 'المستندات المرتبطة',
    aDocumentCannotBeLinked: 'لا يصبح المستند قابلاً للربط والتنزيل حتى يمر بالحجر والفحص ويصبح متاحاً.',
    availableDocumentId: 'معرّف المستند المتاح',
    attach: 'إرفاق',
    downloadThroughAccessDecision: 'تنزيل عبر قرار الوصول',
    activityTimeline: 'الخط الزمني للنشاط',
    actionCompleted: 'اكتمل الإجراء.',
    theDataIsStaleRefresh: 'البيانات قديمة؛ تم طلب التحديث.',
    theActionFailed: 'تعذر تنفيذ الإجراء.',
    submitANewRequest: 'إرسال طلب جديد',
    loadingAvailableDocuments: 'جارٍ تحميل المستندات المتاحة…',
    emptyAvailableDocuments: 'لا توجد مستندات مرخّصة للربط',
    forbiddenDocuments: 'لا تملك صلاحية عرض المستندات المتاحة.',
    documentPickerError: 'تعذر تحميل المستندات المتاحة.',
    operationsAndTasks: 'التشغيل والمهام',
    workDefinitions2: 'تعريفات العمل',
    workflowDefinitions: 'تعريفات سير العمل',
    processAndWorkflowSections: 'أقسام الإجراءات وسير العمل',
    loadingApiReference: 'جارٍ تحميل مرجع API…',
    searchForARecordTask: 'ابحث عن معاملة، مهمة، شخص أو مستند…',
    manageFacilitiesStructurePeopleAnd: 'أدر التجمع ومنشآته وهيكله وأشخاصه من مساحة واحدة.',
    operateWorkThenDefineThe: 'شغّل الأعمال، ثم عرّف البيانات والمسارات التي تحكم انتقالها.',
    markNotificationRead: (title: string) => `تحديد الإشعار كمقروء: ${title}`,
  },
  en: {
    platform: 'Institutional Work Portal',
    switchLanguage: 'العربية',
    signIn: 'Sign in',
    username: 'Username',
    password: 'Password',
    signingIn: 'Signing in…',
    loginError: 'We could not sign you in. Check your credentials and try again.',
    requiredLogin: 'Complete the required fields, then try again.',
    welcomeBack: 'Welcome back',
    loginGuidance: 'Sign in with your internal platform account.',
    internalAccess: 'Access is limited to approved internal accounts',
    developmentAccounts: 'Development accounts (development environment only)',
    usernameRequired: 'Username is required.',
    passwordRequired: 'Password is required.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    enableDarkMode: 'Enable dark mode',
    enableLightMode: 'Enable light mode',
    currentFacility: 'Current work scope',
    myRequests: 'My requests',
    newRequest: 'New request',
    organization: 'Organization',
    organizationStructure: 'Structure and positions',
    peopleAssignments: 'People and assignments',
    temporaryAssignments: 'Temporary assignments',
    identityAccounts: 'Identity accounts',
    administrationNavigation: 'Administration navigation',
    importReview: 'Import review',
    roles: 'Roles',
    capabilities: 'Capabilities',
    roleAssignments: 'Role assignments',
    delegations: 'Delegations',
    supervisoryRelationships: 'Supervisory relationships',
    accessExplanation: 'Access explanation',
    authorizationGroup: 'Access and permissions',
    workflowGroup: 'Workflow',
    workflowTasks: 'Workflow and tasks',
    workDefinitions: 'Work definitions',
    workflowAdmin: 'Workflow administration',
    myTasks: 'My tasks',
    searchScreen: 'Search',
    reportsScreen: 'Reports',
    apiDocs: 'Swagger UI',
    apiDocsBody: 'Inspect the interactive OpenAPI contract in Swagger UI.',
    notifications: 'Notifications',
    profile: 'My profile',
    personalAccess: 'Personal access context',
    classificationPolicies: 'Classification policies',
    fieldAccessTemplates: 'Field access templates',
    closeNotifications: 'Close notifications',
    logout: 'Sign out',
    loadingRequests: 'Loading your requests…',
    listError: 'We could not load your requests. Try again.',
    retry: 'Try again',
    emptyTitle: 'No requests yet',
    emptyBody: 'Create the first request for your current facility to begin.',
    noDescription: 'No description',
    submitted: 'Submitted',
    requestTitle: 'Request title (required)',
    requestDescription: 'Request description (required)',
    titleHelp: 'Write a short title that explains the purpose of the request.',
    descriptionHelp: 'Add the details needed to process the request.',
    submit: 'Submit request',
    submitting: 'Submitting request…',
    validationError: 'Complete the required fields, then submit again.',
    titleRequired: 'Request title is required.',
    descriptionRequired: 'Request description is required.',
    submitError: 'The request was not saved. Check your internal connection and try again.',
    success: 'Your request was submitted',
    successBody: 'The request was saved. An in-app notification will appear here after processing completes.',
    backToRequests: 'Back to my requests',
    loadingDetail: 'Loading request…',
    detailError: 'We could not load the request. Try again.',
    unavailable: 'You cannot open this request, or it is no longer available.',
    refreshNotifications: 'Refresh notifications',
    refreshingNotifications: 'Refreshing notifications…',
    notificationError: 'We could not load notifications. Try again.',
    noNotifications: 'No new notifications',
    read: 'Read',
    unread: 'Unread',
    sessionExpired: 'Your session has expired. Sign in to continue.',
    notFound: 'Page not found',
    notFoundBody: 'Check the address or return to your requests.',
    openNavigation: 'Open primary navigation',
    closeNavigation: 'Close primary navigation',
    navigationTitle: 'Primary navigation',
    services: 'Services',
    platformUser: 'Platform user',
    internalSystem: 'Unified platform',
    rightsReserved: 'All rights reserved © 2026',
    organizationName: 'Eradah and Mental Health Complex',
    officeName: 'Project Management and Institutional Transformation Office',
    ownerName: 'Tariq Alwalidi',
    collapseNavigation: 'Collapse sidebar',
    expandNavigation: 'Expand sidebar',
    facilityA: 'Facility A',
    facilityB: 'Facility B',
    dashboardWelcome: 'Welcome',
    dashboardSummary: 'Here is a summary of requests and notifications in the current facility scope.',
    dashboardRange: 'Display limit: 20 requests',
    overview: 'Overview',
    loadedRequests: 'Loaded requests',
    activeRequests: 'Requests in progress',
    completedRequests: 'Completed requests',
    unreadNotifications: 'Loaded unread notifications',
    currentPageSource: 'From the loaded results',
    loadedNotificationSource: 'From the user notifications loaded',
    analytics: 'Analytics',
    timelineTitle: 'Timeline analytics',
    timelineUnavailableTitle: 'No timeline is available yet',
    timelineUnavailableBody: 'Request trends will appear when the governed aggregation source is published.',
    statusBreakdown: 'Requests by status',
    activeStatus: 'In progress',
    completedStatus: 'Completed',
    otherStatus: 'Other statuses',
    noStatusTitle: 'No statuses to display',
    noStatusBody: 'Create the first request to see a concise status distribution here.',
    recentActivity: 'Available activity',
    openNotifications: 'View notifications',
    noNotificationBody: 'The latest alerts related to facility requests will appear here.',
    noData: 'No data',
    ltr: 'ltr',
    home: 'Home',
    processesAndWorkflow: 'Processes and workflow',
    organization2: 'Organization',
    accountsAndAccess: 'Accounts and access',
    coverage: 'Coverage',
    apiReference: 'API reference',
    documents: 'Documents',
    myWork: 'My work',
    operations: 'Operations',
    productReview: 'Product review',
    enGb: 'en-GB',
    couldNotMarkTheNotification: 'Could not mark the notification as read. Try again.',
    saving: 'Saving…',
    markAsRead: 'Mark as read',
    couldNotLoadMoreNotifications: 'Could not load more notifications.',
    loadingMore: 'Loading more…',
    loadMore: 'Load more',
    organizationAndWorkforce: 'Organization and workforce',
    requestActions: 'Request actions',
    submit2: 'Submit',
    return: 'Return',
    complete: 'Complete',
    linkedDocuments: 'Linked documents',
    aDocumentCannotBeLinked: 'A document cannot be linked or downloaded until quarantine and scanning finish and it becomes available.',
    availableDocumentId: 'Available document ID',
    attach: 'Attach',
    downloadThroughAccessDecision: 'Download through access decision',
    activityTimeline: 'Activity timeline',
    actionCompleted: 'Action completed.',
    theDataIsStaleRefresh: 'The data is stale; refresh requested.',
    theActionFailed: 'The action failed.',
    submitANewRequest: 'Submit a new request',
    loadingAvailableDocuments: 'Loading available documents…',
    emptyAvailableDocuments: 'No authorized documents are available to link.',
    forbiddenDocuments: 'You do not have permission to view available documents.',
    documentPickerError: 'Available documents could not be loaded.',
    operationsAndTasks: 'Operations and tasks',
    workDefinitions2: 'Work definitions',
    workflowDefinitions: 'Workflow definitions',
    processAndWorkflowSections: 'Process and workflow sections',
    loadingApiReference: 'Loading API reference…',
    searchForARecordTask: 'Search for a record, task, person, or document…',
    manageFacilitiesStructurePeopleAnd: 'Manage facilities, structure, people, and assignments from one workspace.',
    operateWorkThenDefineThe: 'Operate work, then define the data and paths that govern it.',
    markNotificationRead: (title: string) => `Mark notification as read: ${title}`,
  },
} as const

export const recordStatusText = {
  ar: {
    draft: 'مسودة',
    submitted: 'تم الإرسال',
    in_review: 'قيد المراجعة',
    returned: 'معاد للتعديل',
    approved: 'معتمد',
    rejected: 'مرفوض',
    completed: 'مكتمل',
    cancelled: 'ملغي',
    archived: 'مؤرشف',
  },
  en: {
    draft: 'Draft',
    submitted: 'Submitted',
    in_review: 'In review',
    returned: 'Returned',
    approved: 'Approved',
    rejected: 'Rejected',
    completed: 'Completed',
    cancelled: 'Cancelled',
    archived: 'Archived',
  },
} as const

export const LOCALE_KEY = 'cluster.presentation-locale'

export function initialLocale(): Locale {
  try {
    return window.localStorage.getItem(LOCALE_KEY) === 'en' ? 'en' : 'ar'
  } catch {
    return 'ar'
  }
}

export function recordStatusLabel(status: string, locale: Locale): string {
  const labels = recordStatusText[locale] as Record<string, string>
  return labels[status] ?? status
}

export type AppCopy = (typeof text)[Locale]

/**
 * Locale metadata used for formatting rather than display. Kept out of the `text`
 * dictionaries because these are BCP 47 tags and a writing direction, not copy.
 */
export function formattingLocale(locale: Locale): string {
  return locale === 'ar' ? 'ar-SA' : 'en-GB'
}

export function numberFormattingLocale(locale: Locale): string {
  return locale === 'ar' ? 'ar-SA-u-nu-arab' : 'en-US'
}

export function directionForLocale(locale: Locale): 'rtl' | 'ltr' {
  return locale === 'ar' ? 'rtl' : 'ltr'
}
