<?php

namespace Tests\Architecture;

final class ModulePlacementInventory
{
    /**
     * Temporary, exact-path inventory of business code that predates the
     * app-placement guard. Entries must be removed as their owning module is
     * migrated. Adding a path requires an explicit architecture-test change.
     *
     * @return list<string>
     */
    public static function misplacedBusinessFiles(): array
    {
        return [
            'app/Http/Controllers/Api/LinkDocumentController.php',
            'app/Http/Controllers/Api/WorkDefinitionController.php',
            'app/Http/Controllers/Api/WorkRecordLifecycleController.php',
            'app/Http/Controllers/Api/WorkflowController.php',
            'app/Http/Controllers/Authorization/AuthorizationAdminController.php',
            'app/Http/Controllers/Authorization/CompleteAuthorizationBootstrapController.php',
            'app/Http/Controllers/Authorization/DecideAccessController.php',
            'app/Http/Controllers/Authorization/ExplainAccessDecisionController.php',
            'app/Http/Controllers/Authorization/GetAuthorizationBootstrapController.php',
            'app/Http/Controllers/Documents/AddDocumentVersionController.php',
            'app/Http/Controllers/Documents/CompleteDocumentUploadController.php',
            'app/Http/Controllers/Documents/CreateDocumentController.php',
            'app/Http/Controllers/Documents/CreateDocumentGrantController.php',
            'app/Http/Controllers/Documents/DocumentAccessSupport.php',
            'app/Http/Controllers/Documents/DownloadDocumentController.php',
            'app/Http/Controllers/Documents/GetDocumentController.php',
            'app/Http/Controllers/Documents/GetDocumentUploadStatusController.php',
            'app/Http/Controllers/Documents/InitiateDocumentUploadController.php',
            'app/Http/Controllers/Documents/LinkDocumentController.php',
            'app/Http/Controllers/Documents/ListDocumentLinksController.php',
            'app/Http/Controllers/Documents/ListDocumentVersionsController.php',
            'app/Http/Controllers/Documents/ListDocumentsController.php',
            'app/Http/Controllers/Documents/ReconcileDocumentPromotionController.php',
            'app/Http/Controllers/Documents/ScanDocumentVersionController.php',
            'app/Http/Controllers/Documents/TransitionDocumentController.php',
            'app/Http/Controllers/Documents/UpdateDocumentController.php',
            'app/Http/Controllers/Identity/ChangePasswordController.php',
            'app/Http/Controllers/Identity/ConsumeActivationController.php',
            'app/Http/Controllers/Identity/CreateUserAccountController.php',
            'app/Http/Controllers/Identity/GetCurrentIdentityController.php',
            'app/Http/Controllers/Identity/GetCurrentPrincipalController.php',
            'app/Http/Controllers/Identity/GetUserAccountController.php',
            'app/Http/Controllers/Identity/IdentityIdempotency.php',
            'app/Http/Controllers/Identity/IdentityLoginController.php',
            'app/Http/Controllers/Identity/IdentityLogoutController.php',
            'app/Http/Controllers/Identity/IssueActivationController.php',
            'app/Http/Controllers/Identity/ListMyScopesController.php',
            'app/Http/Controllers/Identity/ListUserAccountsController.php',
            'app/Http/Controllers/Identity/RefreshIdentityCsrfController.php',
            'app/Http/Controllers/Identity/SelectMyScopeController.php',
            'app/Http/Controllers/Identity/TransitionUserAccountController.php',
            'app/Http/Controllers/Organization/CreateAssignmentController.php',
            'app/Http/Controllers/Organization/CreateClusterController.php',
            'app/Http/Controllers/Organization/CreateFacilityController.php',
            'app/Http/Controllers/Organization/CreateJobTitleController.php',
            'app/Http/Controllers/Organization/CreateOrganizationUnitController.php',
            'app/Http/Controllers/Organization/CreatePersonController.php',
            'app/Http/Controllers/Organization/CreatePositionController.php',
            'app/Http/Controllers/Organization/CreateTemporaryAssignmentController.php',
            'app/Http/Controllers/Organization/EndAssignmentController.php',
            'app/Http/Controllers/Organization/GetClusterController.php',
            'app/Http/Controllers/Organization/GetFacilityController.php',
            'app/Http/Controllers/Organization/GetImportJobController.php',
            'app/Http/Controllers/Organization/GetOrganizationUnitController.php',
            'app/Http/Controllers/Organization/GetPersonController.php',
            'app/Http/Controllers/Organization/GetPersonReferenceController.php',
            'app/Http/Controllers/Organization/GetPositionController.php',
            'app/Http/Controllers/Organization/GetTemporaryAssignmentController.php',
            'app/Http/Controllers/Organization/ListAssignmentsController.php',
            'app/Http/Controllers/Organization/ListFacilitiesController.php',
            'app/Http/Controllers/Organization/ListImportJobRowsController.php',
            'app/Http/Controllers/Organization/ListJobTitlesController.php',
            'app/Http/Controllers/Organization/ListOrganizationUnitsController.php',
            'app/Http/Controllers/Organization/ListPeopleController.php',
            'app/Http/Controllers/Organization/ListPositionsController.php',
            'app/Http/Controllers/Organization/ListTemporaryAssignmentsController.php',
            'app/Http/Controllers/Organization/ReorderOrganizationUnitsController.php',
            'app/Http/Controllers/Organization/RevokeTemporaryAssignmentController.php',
            'app/Http/Controllers/Organization/SubmitImportJobController.php',
            'app/Http/Controllers/Organization/SupervisoryRelationshipController.php',
            'app/Http/Controllers/Organization/TransitionImportJobController.php',
            'app/Http/Controllers/Organization/UpdateClusterController.php',
            'app/Http/Controllers/Organization/UpdateFacilityController.php',
            'app/Http/Controllers/Organization/UpdateOrganizationUnitController.php',
            'app/Http/Controllers/Organization/UpdatePersonController.php',
            'app/Http/Controllers/Organization/UpdatePositionController.php',
            'app/Http/Middleware/ConsumeSubmittedNotification.php',
            'app/Integrations/Notifications/DatabaseTechnicalAlertRecipientResolver.php',
            'app/Integrations/WorkRecordAuthorizationFacts.php',
            'app/Integrations/WorkRecordWorkflowSourceAuthorizationFacts.php',
            'app/Support/OrganizationHierarchyDemoSeeder.php',
            'app/Support/RealisticClusterFacilitiesSeeder.php',
            'app/Support/W12E2EFixtureSeeder.php',
            'Modules/Identity/Features/DevelopmentFixtureLogin/Http/DevelopmentFixtureLoginController.php',
            'Modules/Notifications/Features/ListMyNotifications/Http/ListMyNotificationsController.php',
            'Modules/Notifications/Features/ListMyNotifications/Http/MarkNotificationReadController.php',
            'Modules/Reporting/Http/ListDashboardsController.php',
            'Modules/Reporting/Http/ListReportsController.php',
        ];
    }
}
