export const importsCopy = {
  ar: {
    title: 'مراجعة استيراد البيانات',
    intro: 'ارفع ملف البيانات، ثم راجع النتائج قبل اعتمادها وتطبيقها.',
    loading: 'جارٍ تحميل الاستيراد…',
    retry: 'إعادة المحاولة',
    error: 'تعذر تحميل الاستيراد. أعد المحاولة.',
    stepUpload: '١. رفع الملف',
    stepValidate: '٢. بدء مراجعة الملف',
    stepReview: '٣. مراجعة النتائج',
    stepCommit: '٤. التزام',
    uploadHelp: 'ارفع ملف CSV وفق القالب المحدد. يجب أن يكون الملف بترميز UTF-8.',
    file: 'ملف البيانات',
    template: 'نوع البيانات',
    upload: 'رفع الملف',
    uploading: 'جارٍ رفع الملف…',
    uploadReady: 'اختر ملفاً للبدء.',
    uploadComplete: 'اكتمل رفع الملف. يمكنك الآن بدء مراجعته.',
    uploadError: 'تعذر رفع الملف. حاول مرة أخرى.',
    fileRequired: 'اختر ملف CSV للمتابعة.',
    fileInvalid: 'اختر ملفاً بامتداد CSV.',
    fileTooLarge: 'حجم الملف غير مدعوم (10 ميغابايت كحد أقصى).',
    quarantineId: 'مرجع الملف',
    submit: 'بدء المراجعة',
    validation: 'أدخل مرجعاً صحيحاً.',
    submitError: 'تعذر بدء المراجعة. حاول مرة أخرى.',
    summary: 'ملخص المراجعة',
    rowsTitle: 'نتائج فحص البيانات',
    noRows: 'لم تظهر نتائج الفحص بعد. نفّذ خطوة التحقق أولاً.',
    status: 'الحالة',
    total: 'إجمالي السجلات',
    valid: 'جاهزة',
    errors: 'تحتاج تصحيحاً',
    row: 'رقم السجل',
    proposed: 'ما سيحدث',
    decision: 'القرار',
    validationErrors: 'الملاحظات',
    noErrors: 'جاهز',
    create: 'إنشاء',
    skip: 'تخطي',
    accepted: 'مقبول',
    rejectedDecision: 'مرفوض',
    actionsTitle: 'الخطوة التالية',
    reason: 'سبب الرفض أو الإلغاء',
    execute: 'متابعة',
    executing: 'جارٍ التنفيذ…',
    transitionError: 'تعذر إكمال الخطوة. راجع الحالة والصلاحية.',
    stale: 'بيانات قديمة، حدّث الصفحة ثم أعد المحاولة.',
    received: 'تم استلام الملف',
    validated: 'تم فحص البيانات',
    approved: 'تم الاعتماد',
    rejected: 'مرفوض',
    applied: 'تمت الإضافة',
    cancelled: 'ملغي',
    failed: 'تعذر التنفيذ',
    validate: 'تحقق',
    approve: 'اعتماد',
    reject: 'رفض',
    apply: 'تطبيق',
    cancel: 'إلغاء',
    rejectTitle: 'رفض الاستيراد',
    cancelTitle: 'إلغاء الاستيراد',
    reasonRequired: 'أدخل سبباً واضحاً للمتابعة.',
    noJob: 'لا توجد عملية استيراد قيد المراجعة.',
    facilities: 'المنشآت',
    organizationUnits: 'الوحدات التنظيمية',
    positions: 'المناصب',
    peopleAssignments: 'الموظفون والتكليفات',
    refresh: 'تحديث النتائج',
    showAll: 'عرض الكل',
    showBlockingOnly: 'إظهار المشاكل فقط',
    commitSummary: 'ملخص الالتزام',
    commitConfirm: 'تأكيد التطبيق',
    commitConfirmBody: 'سيُضاف العدد المؤكد من السجلات نهائياً. لا يمكن التراجع بعد التطبيق.',
    back: 'عودة',
  },
  en: {
    title: 'Import review',
    intro: 'Upload the data file, then review the results before approving and applying them.',
    loading: 'Loading import…',
    retry: 'Try again',
    error: 'The import could not be loaded.',
    stepUpload: '1. Upload file',
    stepValidate: '2. Start file review',
    stepReview: '3. Review results',
    stepCommit: '4. Commit',
    uploadHelp: 'Upload a CSV file matching the selected template. The file must be UTF-8 encoded.',
    file: 'Data file',
    template: 'Data type',
    upload: 'Upload file',
    uploading: 'Uploading file…',
    uploadReady: 'Choose a file to start.',
    uploadComplete: 'File uploaded. You can now start its review.',
    uploadError: 'The file could not be uploaded. Try again.',
    fileRequired: 'Choose a CSV file to continue.',
    fileInvalid: 'Choose a file with a CSV extension.',
    fileTooLarge: 'The file size is not supported (10 MiB maximum).',
    quarantineId: 'File reference',
    submit: 'Start review',
    validation: 'Enter a valid reference.',
    submitError: 'The review could not be started. Try again.',
    summary: 'Review summary',
    rowsTitle: 'Data check results',
    noRows: 'No check results yet. Run the validation step first.',
    status: 'Status',
    total: 'Total records',
    valid: 'Ready',
    errors: 'Needs fixing',
    row: 'Record',
    proposed: 'Will happen',
    decision: 'Decision',
    validationErrors: 'Notes',
    noErrors: 'Ready',
    create: 'Create',
    skip: 'Skip',
    accepted: 'Accepted',
    rejectedDecision: 'Rejected',
    actionsTitle: 'Next step',
    reason: 'Rejection or cancellation reason',
    execute: 'Continue',
    executing: 'Executing…',
    transitionError: 'Could not complete the step. Check the status and permission.',
    stale: 'The data is outdated. Refresh the page and try again.',
    received: 'File received',
    validated: 'Data checked',
    approved: 'Approved',
    rejected: 'Rejected',
    applied: 'Applied',
    cancelled: 'Cancelled',
    failed: 'Failed',
    validate: 'Validate',
    approve: 'Approve',
    reject: 'Reject',
    apply: 'Apply',
    cancel: 'Cancel',
    rejectTitle: 'Reject import',
    cancelTitle: 'Cancel import',
    reasonRequired: 'Enter a clear reason to continue.',
    noJob: 'No import is under review.',
    facilities: 'Facilities',
    organizationUnits: 'Organization units',
    positions: 'Positions',
    peopleAssignments: 'People & assignments',
    refresh: 'Refresh results',
    showAll: 'Show all',
    showBlockingOnly: 'Show problems only',
    commitSummary: 'Commit summary',
    commitConfirm: 'Confirm apply',
    commitConfirmBody: 'The confirmed records will be added permanently. This cannot be undone after applying.',
    back: 'Back',
  },
} as const
