export const searchCopy = {
  ar: {
    title: 'بحث',
    description: 'ابحث في المحتوى المصرح لك به فقط. النتائج مقيّدة بالنطاق في الخادم.',
    query: 'نص البحث',
    queryPlaceholder: 'ابحث في المنصة…',
    type: 'النوع',
    status: 'الحالة',
    all: 'الكل',
    submit: 'بحث',
    searching: 'جارٍ البحث…',
    invalidQuery: 'أدخل استعلام بحث صالحًا (من 1 إلى 256 حرفًا).',
    failed: 'تعذر إكمال البحث.',
    noResults: 'لا توجد نتائج',
    noResultsBody: 'جرّب استعلامًا آخر أو وسّع المرشحات.',
    loadMore: 'عرض المزيد',
    loadingMore: 'جارٍ التحميل…',
    retry: 'إعادة المحاولة',
    denied: 'لا يمكن الوصول إلى هذا المحتوى.',
    task: 'مهمة',
    document: 'مستند',
  },
  en: {
    title: 'Search',
    description: 'Search only content you are authorized to see. Results are scope-bound on the server.',
    query: 'Search text',
    queryPlaceholder: 'Search the platform…',
    type: 'Type',
    status: 'Status',
    all: 'All',
    submit: 'Search',
    searching: 'Searching…',
    invalidQuery: 'Enter a valid search query (1 to 256 characters).',
    failed: 'The search could not be completed.',
    noResults: 'No results',
    noResultsBody: 'Try a different query or widen the filters.',
    loadMore: 'Load more',
    loadingMore: 'Loading…',
    retry: 'Retry',
    denied: 'This content cannot be accessed.',
    task: 'Task',
    document: 'Document',
  },
} as const

export type SearchCopy = (typeof searchCopy)['ar']
