
export const organizationCopy = {
  ar: {
    title: 'المنظمة',
    intro: 'بيانات التجمع والهيكل التنظيمي والموظفين في عرض واحد.',
    tabsLabel: 'أقسام المنظمة',
    overviewTab: 'نظرة عامة',
    structureTab: 'الهيكل التنظيمي',
    facilitiesTab: 'المنشآت',
    positionsTab: 'الوظائف',
    jobTitlesTab: 'المسميات الوظيفية',
    peopleTab: 'الموظفون',
    assignmentsTab: 'التكليفات',
    temporaryTab: 'التكليفات المؤقتة',
    supervisoryTab: 'العلاقات الإشرافية',
    clusterTab: 'إعداد المجمّع',
    unavailable: 'غير متاح',
    loading: 'جارٍ التحميل…',
    retry: 'إعادة المحاولة',
    error: 'تعذر تحميل البيانات. أعد المحاولة.',
    addCluster: 'إضافة تجمع',
    addFacility: 'إضافة منشأة',
    editCluster: 'تعديل بيانات التجمع',
    editFacility: 'تعديل المنشأة',
    cluster: 'بيانات التجمع',
    facilities: 'المنشآت',
    noCluster: 'لم تُضف بيانات التجمع بعد.',
    noFacilities: 'لا توجد منشآت بعد.',
    identifier: 'الرقم التعريفي',
    type: 'النوع',
    status: 'الحالة',
    actions: 'الإجراءات',
    active: 'نشط',
    inactive: 'غير نشط',
    archived: 'مؤرشف',
    hospital: 'مستشفى',
    center: 'مركز صحي',
    lab: 'مختبر',
    sharedServices: 'خدمات مشتركة',
    clusterSaved: 'تم حفظ بيانات التجمع.',
    facilitySaved: 'تم حفظ بيانات المنشأة.',
    unitSaved: 'تم حفظ الوحدة.',
    positionSaved: 'تم حفظ المنصب.',
    personSaved: 'تم حفظ بيانات الموظف.',
    assignmentSaved: 'تم إنشاء التكليف.',
    assignmentEnded: 'تم إنهاء التكليف.',
    createClusterTitle: 'إضافة تجمع',
    editClusterTitle: 'تعديل بيانات التجمع',
    createFacilityTitle: 'إضافة منشأة',
    editFacilityTitle: 'تعديل المنشأة',
    createUnitTitle: 'إضافة وحدة',
    createPositionTitle: 'إضافة منصب',
    createPersonTitle: 'إضافة موظف',
    editPersonTitle: 'تعديل بيانات الموظف',
    createAssignmentTitle: 'إنشاء تكليف',
    endAssignmentTitle: 'إنهاء التكليف',
    code: 'الرقم التعريفي',
    codeHint:
      'استخدم حروفاً إنجليزية كبيرة وأرقاماً وشرطة أو شرطة سفلية فقط (2–64).',
    nameAr: 'الاسم بالعربية',
    nameEn: 'الاسم بالإنجليزية',
    cancel: 'إلغاء',
    save: 'حفظ',
    saving: 'جارٍ الحفظ…',
    close: 'إغلاق',
    confirm: 'تأكيد',
    validation: 'أكمل الحقول المطلوبة بالصيغة الصحيحة.',
    stale: 'تغيّرت البيانات في مكان آخر. حدّث الصفحة ثم أعد المحاولة.',
    saveError: 'تعذر حفظ البيانات. أعد المحاولة.',
    rootLevel: 'على مستوى التجمع',
    unitType: 'نوع الوحدة',
    sector: 'قطاع',
    department: 'إدارة',
    section: 'قسم',
    unit: 'وحدة',
    parent: 'الموقع الأعلى',
    jobTitle: 'المسمى الوظيفي',
    positionTitle: 'العنوان',
    addUnit: 'إضافة وحدة',
    addPosition: 'إضافة منصب',
    addJobTitle: 'إضافة مسمى وظيفي',
    noJobTitles: 'لا توجد مسميات وظيفية بعد.',
    jobTitleSaved: 'تم حفظ المسمى الوظيفي.',
    addPerson: 'إضافة موظف',
    createAssignment: 'إنشاء تكليف',
    endAssignment: 'إنهاء التكليف',
    reorder: 'ترتيب الوحدات',
    reorderConfirm:
      'سيُرتَّب كل مستوى من الوحدات بحسب النوع ثم الاسم. هل تريد المتابعة؟',
    reorderBusy: 'جارٍ ترتيب الوحدات…',
    reorderFailed: 'تعذّر ترتيب الوحدات. أعد المحاولة.',
    reorderStale: 'بيانات قديمة، حدّث الصفحة ثم أعد المحاولة.',
    reorderSuccess: (count: string) => `تم ترتيب ${count} وحدة.`,
    unitsAtCluster: 'وحدات على مستوى التجمع',
    unitPositions: 'المناصب',
    noUnits: 'لا توجد وحدات بعد.',
    noPositions: 'لا توجد مناصب لهذه الوحدة.',
    people: 'الموظفون',
    assignments: 'التكليفات',
    employee: 'الموظف',
    employeeNumber: 'الرقم الوظيفي',
    person: 'الموظف',
    position: 'المنصب',
    startAt: 'بداية التكليف',
    endAt: 'نهاية التكليف',
    endReason: 'سبب الإنهاء',
    endReasonHelp: 'أدخل سبباً واضحاً لإنهاء التكليف.',
    noPeople: 'لا يوجد موظفون بعد.',
    noAssignments: 'لا توجد تكليفات بعد.',
    primary: 'أساسي',
    noActivePeople: 'أضف موظفاً نشطاً واحداً على الأقل قبل إنشاء تكليف.',
    noActivePositions: 'أضف منصباً نشطاً واحداً على الأقل قبل إنشاء تكليف.',
    endAtRequired: 'أدخل وقت نهاية التكليف وسبباً واضحاً بعد بداية التكليف.',
    edit: 'تعديل',
    suspended: 'موقوف',
    left: 'غادر',
    pending: 'قادم',
    ended: 'منتهٍ',
    countBadge: (count: string) => `${count} عنصر`,
    remaining: 'المدة المتبقية',
    remainingDays: 'تبقّى {n} أيام',
    remainingHours: 'تبقّى {n} ساعات',
    noSupervisory: 'لا توجد علاقات إشرافية بعد.',
    relationshipType: 'نوع العلاقة',
  },
  en: {
    title: 'Organization',
    intro:
      'Cluster information, organization structure, and employees in one view.',
    tabsLabel: 'Organization sections',
    overviewTab: 'Overview',
    structureTab: 'Structure',
    facilitiesTab: 'Facilities',
    positionsTab: 'Positions',
    jobTitlesTab: 'Job titles',
    peopleTab: 'People',
    assignmentsTab: 'Assignments',
    temporaryTab: 'Temporary assignments',
    supervisoryTab: 'Supervisory relationships',
    clusterTab: 'Cluster settings',
    unavailable: 'Unavailable',
    loading: 'Loading…',
    retry: 'Try again',
    error: 'The data could not be loaded. Try again.',
    addCluster: 'Add cluster',
    addFacility: 'Add facility',
    editCluster: 'Edit cluster information',
    editFacility: 'Edit facility',
    cluster: 'Cluster information',
    facilities: 'Facilities',
    noCluster: 'Cluster information has not been added yet.',
    noFacilities: 'No facilities yet.',
    identifier: 'Identifier',
    type: 'Type',
    status: 'Status',
    actions: 'Actions',
    active: 'Active',
    inactive: 'Inactive',
    archived: 'Archived',
    hospital: 'Hospital',
    center: 'Health center',
    lab: 'Laboratory',
    sharedServices: 'Shared services',
    clusterSaved: 'Cluster information saved.',
    facilitySaved: 'Facility information saved.',
    unitSaved: 'Unit saved.',
    positionSaved: 'Position saved.',
    personSaved: 'Employee saved.',
    assignmentSaved: 'Assignment created.',
    assignmentEnded: 'Assignment ended.',
    createClusterTitle: 'Add cluster',
    editClusterTitle: 'Edit cluster information',
    createFacilityTitle: 'Add facility',
    editFacilityTitle: 'Edit facility',
    createUnitTitle: 'Add unit',
    createPositionTitle: 'Add position',
    createPersonTitle: 'Add employee',
    editPersonTitle: 'Edit employee details',
    createAssignmentTitle: 'Create assignment',
    endAssignmentTitle: 'End assignment',
    code: 'Identifier',
    codeHint:
      'Use uppercase letters, digits, hyphens, or underscores only (2–64).',
    nameAr: 'Name in Arabic',
    nameEn: 'Name in English',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    close: 'Close',
    confirm: 'Confirm',
    validation: 'Complete the required fields using the expected format.',
    stale:
      'This information changed elsewhere. Refresh the page and try again.',
    saveError: 'The data could not be saved. Try again.',
    rootLevel: 'At cluster level',
    unitType: 'Unit type',
    sector: 'Sector',
    department: 'Department',
    section: 'Section',
    unit: 'Unit',
    parent: 'Higher level',
    jobTitle: 'Job title',
    positionTitle: 'Title',
    addUnit: 'Add unit',
    addPosition: 'Add position',
    addJobTitle: 'Add job title',
    noJobTitles: 'No job titles yet.',
    jobTitleSaved: 'Job title saved.',
    addPerson: 'Add employee',
    createAssignment: 'Create assignment',
    endAssignment: 'End assignment',
    reorder: 'Arrange units',
    reorderConfirm:
      'This will arrange units at each level by type, then name. Continue?',
    reorderBusy: 'Arranging units…',
    reorderFailed: 'The units could not be arranged. Try again.',
    reorderStale: 'The data is outdated. Refresh the page and try again.',
    reorderSuccess: (count: string) => `${count} units arranged.`,
    unitsAtCluster: 'Units at cluster level',
    unitPositions: 'Positions',
    noUnits: 'No units yet.',
    noPositions: 'No positions for this unit.',
    people: 'Employees',
    assignments: 'Assignments',
    employee: 'Employee',
    employeeNumber: 'Employee number',
    person: 'Employee',
    position: 'Position',
    startAt: 'Assignment start',
    endAt: 'Assignment end',
    endReason: 'End reason',
    endReasonHelp: 'Enter a clear reason for ending the assignment.',
    noPeople: 'No employees yet.',
    noAssignments: 'No assignments yet.',
    primary: 'Primary',
    noActivePeople:
      'Add at least one active employee before creating an assignment.',
    noActivePositions:
      'Add at least one active position before creating an assignment.',
    endAtRequired:
      'Enter an end time and a clear reason after the assignment start.',
    edit: 'Edit',
    suspended: 'Suspended',
    left: 'Left',
    pending: 'Pending',
    ended: 'Ended',
    countBadge: (count: string) => `${count} items`,
    remaining: 'Remaining',
    remainingDays: '{n} days left',
    remainingHours: '{n} hours left',
    noSupervisory: 'No supervisory relationships yet.',
    relationshipType: 'Relationship type',
  },
} as const
