import { useState } from 'react'
import { Button, Drawer, Panel, StatusBadge } from '../../ui'
import { isAllowed, screenText, stateGate, type PlatformScreenProps } from './screen-support'

export function MaintenanceScreen({ locale, state = 'success', allowedActions }: PlatformScreenProps) {
  const [createOpen, setCreateOpen] = useState(false)
  const [cancelOpen, setCancelOpen] = useState(false)
  const gate = stateGate(locale, state, screenText(locale, 'لا توجد نوافذ صيانة', 'No maintenance windows are scheduled'))
  if (gate) return gate
  return <div className="platform-screen"><Panel id="maintenance-current" title={screenText(locale, 'الحالة الحالية', 'Current status')}><p>{screenText(locale, 'وضع الصيانة غير نشط. ستظهر رسالة ثنائية اللغة للمستخدمين المتأثرين عند التفعيل.', 'Maintenance mode is inactive. A bilingual message will be shown to affected users when activated.')}</p><StatusBadge variant="success">{screenText(locale, 'متاح', 'Available')}</StatusBadge></Panel><Panel id="maintenance-upcoming" title={screenText(locale, 'النوافذ القادمة', 'Upcoming windows')}><ul className="platform-activity-list"><li>{screenText(locale, 'الخميس 30 يوليو، 01:00–02:00 — تحديث مجدول', 'Thursday 30 July, 01:00–02:00 — Scheduled update')}</li></ul><div className="platform-action-row">{isAllowed(allowedActions, 'platform_operations.maintenance.manage') ? <Button onClick={() => setCreateOpen(true)}>{screenText(locale, 'إنشاء نافذة صيانة', 'Create maintenance window')}</Button> : null}{isAllowed(allowedActions, 'platform_operations.maintenance.cancel') ? <Button variant="secondary" onClick={() => setCancelOpen(true)}>{screenText(locale, 'إلغاء النافذة', 'Cancel window')}</Button> : null}</div></Panel><Drawer open={createOpen} onClose={() => setCreateOpen(false)} title={screenText(locale, 'إنشاء نافذة صيانة', 'Create maintenance window')}><p>{screenText(locale, 'تحتوي النافذة على البداية والنهاية والسبب ورسالتين بالعربية والإنجليزية.', 'The window contains start, end, reason, and Arabic and English messages.')}</p><Button onClick={() => setCreateOpen(false)}>{screenText(locale, 'إنشاء', 'Create')}</Button></Drawer><Drawer open={cancelOpen} onClose={() => setCancelOpen(false)} title={screenText(locale, 'تأكيد إلغاء النافذة', 'Confirm window cancellation')}><p>{screenText(locale, 'يتطلب الإلغاء تأكيداً مستقلاً.', 'Cancellation requires a separate confirmation.')}</p><Button onClick={() => setCancelOpen(false)}>{screenText(locale, 'تأكيد الإلغاء', 'Confirm cancellation')}</Button></Drawer></div>
}
