import { Activity } from 'lucide-react'
import { useState } from 'react'
import { Button, DataFreshness, Drawer, Panel, StatusBadge } from '../../ui'
import { isAllowed, screenText, stateGate, type PlatformScreenProps } from './screen-support'

export function PlatformHealthScreen({ locale, state = 'success', allowedActions }: PlatformScreenProps) {
  const [policyOpen, setPolicyOpen] = useState(false)
  const gate = stateGate(locale, state, screenText(locale, 'لا توجد نتائج صحة', 'No health checks are available'))
  if (gate) return gate
  return <div className="platform-screen"><DataFreshness state={state === 'stale' ? 'stale' : 'fresh'} updatedAt={screenText(locale, 'فُحصت 09:30', 'Checked 09:30')} staleAfterMinutes={15} /><Panel id="health-services" title={screenText(locale, 'الخدمات', 'Services')}><ul className="platform-status-list"><li><Activity aria-hidden="true" /><span>Database — 18ms</span><StatusBadge variant="success">{screenText(locale, 'سليم', 'Healthy')}</StatusBadge></li><li><Activity aria-hidden="true" /><span>Redis — 220ms</span><StatusBadge variant="warning">{screenText(locale, 'متدهور', 'Degraded')}</StatusBadge></li><li><Activity aria-hidden="true" /><span>Storage — 32ms</span><StatusBadge variant="success">{screenText(locale, 'سليم', 'Healthy')}</StatusBadge></li></ul></Panel><Panel id="alert-policies" title={screenText(locale, 'سياسات التوجيه', 'Routing policies')}><ul className="platform-activity-list"><li>{screenText(locale, 'الحرج ← داخل التطبيق + البريد ← تصعيد بعد 15 دقيقة', 'Critical → in-app + email → escalate after 15 minutes')}</li><li>{screenText(locale, 'التحذير ← داخل التطبيق', 'Warning → in-app')}</li></ul>{isAllowed(allowedActions, 'platform_operations.alerts.manage') ? <Button variant="secondary" onClick={() => setPolicyOpen(true)}>{screenText(locale, 'تعديل سياسات التوجيه', 'Edit routing policies')}</Button> : null}</Panel><Drawer open={policyOpen} onClose={() => setPolicyOpen(false)} title={screenText(locale, 'تعديل سياسات التوجيه', 'Edit routing policies')}><p>{screenText(locale, 'تغييرات التوجيه تخضع لحدود الأمان الثابتة وتحتاج نشرًا صريحًا.', 'Routing changes stay within fixed security limits and require explicit publication.')}</p><div className="platform-action-row"><Button onClick={() => setPolicyOpen(false)}>{screenText(locale, 'حفظ المسودة', 'Save draft')}</Button><Button variant="quiet" onClick={() => setPolicyOpen(false)}>{screenText(locale, 'إلغاء', 'Cancel')}</Button></div></Drawer></div>
}
