export const accountsCopy = {
  ar: {
    title: 'الحسابات والصلاحيات',
    intro: 'أدر حسابات الدخول والأدوار وافحص قرارات الوصول.',
    tabsLabel: 'مساحات الحسابات والصلاحيات',
    tabAccounts: 'الحسابات',
    tabRoles: 'الأدوار',
    tabDiagnostics: 'تشخيص الوصول',
    tabBootstrap: 'التهيئة',
    unavailable: 'غير متاح',
    unavailableBody: 'لا تملك الصلاحية المطلوبة لعرض هذا القسم.',
    retry: 'إعادة المحاولة',
    loading: 'جارٍ التحميل…',
    close: 'إغلاق',
    save: 'حفظ',
    cancel: 'إلغاء',
    done: 'تم تنفيذ الإجراء.',
    saveError: 'لم يُحفظ التغيير. أعد المحاولة.',
    stale: 'تغيّرت البيانات من مكان آخر. حدّث القائمة وأعد المحاولة.',
  },
  en: {
    title: 'Accounts & Permissions',
    intro: 'Manage sign-in accounts, roles, and inspect access decisions.',
    tabsLabel: 'Accounts & permissions workspaces',
    tabAccounts: 'Accounts',
    tabRoles: 'Roles',
    tabDiagnostics: 'Access diagnostics',
    tabBootstrap: 'Bootstrap',
    unavailable: 'Unavailable',
    unavailableBody:
      'You do not have the required permission to view this section.',
    retry: 'Retry',
    loading: 'Loading…',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    done: 'Action completed.',
    saveError: 'The change was not saved. Try again.',
    stale: 'This data changed elsewhere. Refresh the list and try again.',
  },
} as const

export const accountCopy = {
  ar: {
    accounts: 'حسابات الدخول',
    noAccounts: 'لا توجد حسابات دخول بعد.',
    noAccountsBody: 'ابدأ بإنشاء حساب لموظف حتى يتمكن من تسجيل الدخول.',
    employee: 'الموظف',
    username: 'اسم الدخول',
    status: 'الحالة',
    actions: 'الإجراءات',
    manage: 'إدارة',
    manageAccount: 'إدارة الحساب',
    addAccount: 'إضافة حساب',
    addAccountTitle: 'إضافة حساب دخول',
    addAccountIntro:
      'اختر الموظف واكتب اسم الدخول. يُنشأ الحساب بانتظار التفعيل.',
    create: 'إنشاء الحساب',
    saving: 'جارٍ الحفظ…',
    usernameHint: '٣ أحرف فأكثر: حروف إنجليزية وأرقام و . _ - فقط.',
    validation: 'اختر موظفاً واكتب اسم دخول صحيحاً.',
    peopleError: 'تعذّر تحميل قائمة الموظفين.',
    reason: 'سبب الإجراء (اختياري)',
    reasonHint: 'يُحفظ في سجل التدقيق ليُعرف لاحقاً سبب التغيير.',
    pending: 'بانتظار التفعيل',
    active: 'نشط',
    locked: 'مقفل',
    disabled: 'معطَّل',
    archived: 'مؤرشف',
    mustChangePassword: 'مطلوب من الموظف تغيير كلمة المرور عند الدخول القادم.',
    activate: 'تفعيل الحساب',
    unlock: 'فك القفل',
    disable: 'تعطيل الحساب',
    archive: 'أرشفة الحساب',
    revokeSessions: 'إنهاء الجلسات المفتوحة',
    forcePasswordChange: 'إلزامه بتغيير كلمة المرور',
    noActions: 'لا توجد إجراءات متاحة على هذا الحساب.',
    activateHint: 'يعيد للموظف القدرة على تسجيل الدخول.',
    unlockHint: 'يلغي القفل الناتج عن محاولات الدخول الفاشلة.',
    disableHint: 'يمنع الدخول مؤقتاً مع الاحتفاظ بالحساب.',
    archiveHint: 'إغلاق نهائي للحساب. لا يمكن التراجع.',
    revokeSessionsHint: 'يخرج الموظف من كل الأجهزة فوراً.',
    forcePasswordChangeHint: 'يطلب منه كلمة مرور جديدة عند الدخول القادم.',
    activationIssued: 'تم إصدار رمز التفعيل',
    activationControlledDelivery:
      'يُسلَّم الرمز للموظف عبر القناة الآمنة المخصصة ولا يُعرض في هذه الشاشة أبداً.',
    activationExpiryLabel: 'تنتهي صلاحية الرمز في',
    activationDismiss: 'تم',
    activationFailed: 'تعذّر إصدار رمز التفعيل. أعد المحاولة.',
    accountsError: 'تعذّر تحميل الحسابات.',
    saveError: 'لم يُحفظ التغيير. أعد المحاولة.',
    peopleLoading: 'جارٍ تحميل الموظفين…',
    peopleEmpty: 'لا يوجد موظفون متاحون لإضافة حساب لهم.',
    peoplePickerPlaceholder: 'ابحث عن الموظف أو اختره…',
    peoplePickerLabel: 'قائمة الموظفين',
    peoplePickerEmpty: 'لا يطابق البحث أي موظف.',
    peoplePickerDenied: 'لا يمكن الوصول إلى قائمة الموظفين.',
    peopleLoadMore: 'تحميل المزيد',
  },
  en: {
    accounts: 'Sign-in accounts',
    noAccounts: 'No sign-in accounts yet.',
    noAccountsBody: 'Start by creating an account so an employee can sign in.',
    employee: 'Employee',
    username: 'Username',
    status: 'Status',
    actions: 'Actions',
    manage: 'Manage',
    manageAccount: 'Manage account',
    addAccount: 'Add account',
    addAccountTitle: 'Add a sign-in account',
    addAccountIntro:
      'Pick the employee and choose a username. The account starts as awaiting activation.',
    create: 'Create account',
    saving: 'Saving…',
    usernameHint: 'At least 3 characters: letters, digits, and . _ - only.',
    validation: 'Select an employee and enter a valid username.',
    peopleError: 'Could not load the employee list.',
    reason: 'Reason (optional)',
    reasonHint:
      'Stored in the audit trail so the change can be explained later.',
    pending: 'Awaiting activation',
    active: 'Active',
    locked: 'Locked',
    disabled: 'Disabled',
    archived: 'Archived',
    mustChangePassword: 'The employee must set a new password at next sign-in.',
    activate: 'Activate account',
    unlock: 'Unlock',
    disable: 'Disable account',
    archive: 'Archive account',
    revokeSessions: 'End open sessions',
    forcePasswordChange: 'Require a password change',
    noActions: 'No actions are available on this account.',
    activateHint: 'Restores the employee’s ability to sign in.',
    unlockHint: 'Clears the lock caused by failed sign-in attempts.',
    disableHint: 'Blocks sign-in temporarily while keeping the account.',
    archiveHint: 'Closes the account for good. This cannot be undone.',
    revokeSessionsHint: 'Signs the employee out of every device immediately.',
    forcePasswordChangeHint: 'Asks for a new password at their next sign-in.',
    activationIssued: 'Activation issued',
    activationControlledDelivery:
      'The activation secret is delivered to the employee through the controlled secure channel and is never shown on this screen.',
    activationExpiryLabel: 'The activation expires at',
    activationDismiss: 'Done',
    activationFailed: 'The activation could not be issued. Try again.',
    accountsError: 'Accounts could not be loaded.',
    saveError: 'The change was not saved. Try again.',
    peopleLoading: 'Loading employees…',
    peopleEmpty: 'No employees are available to attach an account to.',
    peoplePickerPlaceholder: 'Search or pick an employee…',
    peoplePickerLabel: 'Employees',
    peoplePickerEmpty: 'No employees match your search.',
    peoplePickerDenied: 'The employee list cannot be accessed.',
    peopleLoadMore: 'Load more',
  },
} as const

export const roleCopy = {
  ar: {
    roles: 'الأدوار والصلاحيات',
    resourceRoles: 'الأدوار',
    resourceCapabilities: 'القدرات',
    resourceAssignments: 'التعيينات',
    resourcesToolbar: 'أدوار وقدرات وتعيينات',
    code: 'رمز الدور',
    name: 'اسم الدور',
    capabilities: 'الصلاحيات',
    create: 'إنشاء دور',
    save: 'حفظ التغييرات',
    edit: 'تعديل',
    archive: 'أرشفة',
    clone: 'نسخ كدور مخصص',
    revoke: 'إزالة',
    expire: 'إنهاء',
    cancel: 'إلغاء',
    saving: 'جارٍ الحفظ…',
    empty: 'لا توجد أدوار لعرضها.',
    noCatalog:
      'لا تتوفر قائمة الصلاحيات (تحتاج authorization.capability.read).',
    roleError: 'تعذّر حفظ الدور.',
    rolesError: 'تعذّر تحميل الأدوار.',
    countCapabilities: 'صلاحية',
    systemRole: 'نظامي',
    customRole: 'مخصص',
    createRoleTitle: 'إنشاء دور',
    editRoleTitle: 'تعديل الدور',
    roleSheetIntro: 'الاسم والرمز والصلاحيات الممنوحة للدور.',
    codeHint: 'حروف إنجليزية صغيرة وأرقام ونقاط وشرطات سفلية.',
    createError: 'تعذّر إنشاء الدور.',
    updateError: 'تعذّر تحديث الدور.',
    archiveTitle: 'أرشفة الدور',
    archiveBody: 'سيُؤرشف الدور ولن يعود قابلاً للاستخدام. هذا الإجراء نهائي.',
    confirm: 'تأكيد',
    capabilitiesEmpty: 'لا توجد قدرات لعرضها.',
    capabilityCode: 'رمز القدرة',
    capabilityModule: 'الوحدة',
    capabilityAction: 'الإجراء',
    capabilitySensitivity: 'الحساسية',
    capabilityGroup: 'المجموعة',
    sensitivityPublic: 'عام',
    sensitivityInternal: 'داخلي',
    sensitivityConfidential: 'سري',
    sensitivityTopSecret: 'سري للغاية',
    sensitiveCapability: 'قدرة حساسة',
    subject: 'المستخدم',
    assignmentRole: 'الدور',
    assignmentScope: 'النطاق',
    assignmentStatus: 'الحالة',
    assignmentWindow: 'الفترة',
    addAssignment: 'إضافة تعيين',
    addAssignmentTitle: 'إضافة تعيين دور',
    assignmentIntro: 'منح دور لمستخدم في نطاق محدد.',
    assignmentAccount: 'الحساب',
    assignmentRoleLabel: 'الدور',
    assignmentScopeTypeLabel: 'نوع النطاق',
    assignmentScopeTargetLabel: 'النطاق',
    assignmentStartLabel: 'البداية',
    assignmentEndLabel: 'النهاية',
    assignmentStartHint: 'مطلوب. يُفعَّل التعيين عند بدايته.',
    assignmentEndHint: 'اختياري. يُنهى التعيين عند نهايته.',
    assignmentStartRequired: 'البداية مطلوبة.',
    assignmentWindowInvalid: 'يجب أن تكون النهاية بعد البداية.',
    assignmentCreate: 'إنشاء التعيين',
    assignmentError: 'تعذّر حفظ التعيين.',
    assignmentValidation: 'اختر الحساب والدور والنطاق.',
    assignmentAccountMissing: 'لا توجد حسابات متاحة.',
    assignmentRoleMissing: 'لا توجد أدوار نشطة.',
    assignmentAccountPickerPlaceholder: 'ابحث عن الحساب أو اختره…',
    assignmentAccountPickerLabel: 'قائمة الحسابات',
    assignmentAccountPickerEmpty: 'لا يطابق البحث أي حساب.',
    assignmentAccountPickerDenied: 'لا يمكن الوصول إلى قائمة الحسابات.',
    assignmentAccountPickerError: 'تعذّر تحميل الحسابات.',
    assignmentAccountPickerLoading: 'جارٍ تحميل الحسابات…',
    assignmentAccountLoadMore: 'تحميل المزيد من الحسابات',
    assignmentRolePickerPlaceholder: 'ابحث عن الدور أو اختره…',
    assignmentRolePickerLabel: 'قائمة الأدوار',
    assignmentRolePickerEmpty: 'لا يطابق البحث أي دور.',
    assignmentRolePickerDenied: 'لا يمكن الوصول إلى قائمة الأدوار.',
    assignmentRolePickerError: 'تعذّر تحميل الأدوار.',
    assignmentRolePickerLoading: 'جارٍ تحميل الأدوار…',
    assignmentRoleLoadMore: 'تحميل المزيد من الأدوار',
    assignmentActivate: 'تفعيل',
    assignmentActivateTitle: 'تفعيل التعيين',
    assignmentActivateBody: 'سيُفعَّل التعيين فوراً ويُمنح المستخدم صلاحية الدور.',
    assignmentExpireTitle: 'إنهاء التعيين',
    assignmentExpireBody: 'سيُنهى التعيين فوراً وتُسحب الصلاحية.',
    assignmentRevokeTitle: 'إزالة التعيين',
    assignmentRevokeBody: 'ستُزال صلاحية الدور من المستخدم نهائياً.',
    assignmentsEmpty: 'لا توجد تعيينات لعرضها.',
    scopeCluster: 'المجموعة',
    scopeFacility: 'المنشأة',
    scopeUnit: 'الوحدة',
    scopeSearchLabel: 'ابحث عن النطاق',
    scopeSearchPlaceholder: 'اكتب للبحث عن النطاق…',
    scopeSelectPlaceholder: 'اختر النطاق',
    scopeNoResults: 'لا توجد نطاقات مطابقة.',
    scopeSearching: 'جارٍ البحث عن النطاقات…',
    scopeSearchError: 'تعذّر البحث عن النطاقات.',
    scopeSearchDenied: 'لا يمكن الوصول إلى هذا المحتوى.',
    unavailable: 'غير متاح',
    effectivePending: 'بانتظار التفعيل',
    effectiveActive: 'نشط',
    effectiveExpired: 'منتهٍ',
    effectiveRevoked: 'مُزال',
  },
  en: {
    roles: 'Roles & Permissions',
    resourceRoles: 'Roles',
    resourceCapabilities: 'Capabilities',
    resourceAssignments: 'Assignments',
    resourcesToolbar: 'Roles, capabilities and assignments',
    code: 'Role code',
    name: 'Role name',
    capabilities: 'Capabilities',
    create: 'Create role',
    save: 'Save changes',
    edit: 'Edit',
    archive: 'Archive',
    clone: 'Clone as custom role',
    revoke: 'Remove',
    expire: 'Expire',
    cancel: 'Cancel',
    saving: 'Saving…',
    empty: 'No roles to display.',
    noCatalog:
      'Capability catalog unavailable (needs authorization.capability.read).',
    roleError: 'Could not save the role.',
    rolesError: 'Roles could not be loaded.',
    countCapabilities: 'capabilities',
    systemRole: 'System',
    customRole: 'Custom',
    createRoleTitle: 'Create role',
    editRoleTitle: 'Edit role',
    roleSheetIntro: 'The name, code, and permissions granted to the role.',
    codeHint: 'Lowercase letters, digits, dots, and underscores.',
    createError: 'Could not create the role.',
    updateError: 'Could not update the role.',
    archiveTitle: 'Archive role',
    archiveBody: 'The role will be archived and can no longer be used. This cannot be undone.',
    confirm: 'Confirm',
    capabilitiesEmpty: 'No capabilities to display.',
    capabilityCode: 'Capability code',
    capabilityModule: 'Module',
    capabilityAction: 'Action',
    capabilitySensitivity: 'Sensitivity',
    capabilityGroup: 'Group',
    sensitivityPublic: 'Public',
    sensitivityInternal: 'Internal',
    sensitivityConfidential: 'Confidential',
    sensitivityTopSecret: 'Top secret',
    sensitiveCapability: 'Sensitive capability',
    subject: 'User',
    assignmentRole: 'Role',
    assignmentScope: 'Scope',
    assignmentStatus: 'Status',
    assignmentWindow: 'Period',
    addAssignment: 'Add assignment',
    addAssignmentTitle: 'Add role assignment',
    assignmentIntro: 'Grant a role to a user within a specific scope.',
    assignmentAccount: 'Account',
    assignmentRoleLabel: 'Role',
    assignmentScopeTypeLabel: 'Scope type',
    assignmentScopeTargetLabel: 'Scope',
    assignmentStartLabel: 'Start',
    assignmentEndLabel: 'End',
    assignmentStartHint: 'Required. The assignment activates at its start.',
    assignmentEndHint: 'Optional. The assignment expires at its end.',
    assignmentStartRequired: 'Start is required.',
    assignmentWindowInvalid: 'The end must be strictly after the start.',
    assignmentCreate: 'Create assignment',
    assignmentError: 'Could not save the assignment.',
    assignmentValidation: 'Select the account, role, and scope.',
    assignmentAccountMissing: 'No accounts available.',
    assignmentRoleMissing: 'No active roles.',
    assignmentAccountPickerPlaceholder: 'Search or pick an account…',
    assignmentAccountPickerLabel: 'Accounts',
    assignmentAccountPickerEmpty: 'No accounts match your search.',
    assignmentAccountPickerDenied: 'The account list cannot be accessed.',
    assignmentAccountPickerError: 'Accounts could not be loaded.',
    assignmentAccountPickerLoading: 'Loading accounts…',
    assignmentAccountLoadMore: 'Load more accounts',
    assignmentRolePickerPlaceholder: 'Search or pick a role…',
    assignmentRolePickerLabel: 'Roles',
    assignmentRolePickerEmpty: 'No roles match your search.',
    assignmentRolePickerDenied: 'The role list cannot be accessed.',
    assignmentRolePickerError: 'Roles could not be loaded.',
    assignmentRolePickerLoading: 'Loading roles…',
    assignmentRoleLoadMore: 'Load more roles',
    assignmentActivate: 'Activate',
    assignmentActivateTitle: 'Activate assignment',
    assignmentActivateBody: 'The assignment will activate immediately and the user is granted the role permission.',
    assignmentExpireTitle: 'Expire assignment',
    assignmentExpireBody: 'The assignment will expire immediately and the permission is withdrawn.',
    assignmentRevokeTitle: 'Remove assignment',
    assignmentRevokeBody: 'The role permission will be permanently removed from the user.',
    assignmentsEmpty: 'No assignments to display.',
    scopeCluster: 'Cluster',
    scopeFacility: 'Facility',
    scopeUnit: 'Unit',
    scopeSearchLabel: 'Search for a scope',
    scopeSearchPlaceholder: 'Type to search for a scope…',
    scopeSelectPlaceholder: 'Select a scope',
    scopeNoResults: 'No matching scopes.',
    scopeSearching: 'Searching for scopes…',
    scopeSearchError: 'Scope search failed.',
    scopeSearchDenied: 'This content cannot be accessed.',
    unavailable: 'Unavailable',
    effectivePending: 'Pending',
    effectiveActive: 'Active',
    effectiveExpired: 'Expired',
    effectiveRevoked: 'Revoked',
  },
} as const

export const diagnosticsCopy = {
  ar: {
    inspector: 'مفتش قرارات الوصول',
    inspectorIntro: 'أدخل معرّف القرار لعرض شرحه الكامل.',
    technicalNotice:
      'شاشة تشخيص تقنية مخصصة للمسؤولين — استثناء موثّق من قاعدة «مصطلح المستخدم لا مصطلح المعماري» (قانون التصميم 2.5).',
    decisionId: 'معرّف القرار',
    inspect: 'فحص',
    inspecting: 'جارٍ الفحص…',
    idle: 'أدخل معرّف قرار لعرض شرحه.',
    allow: 'مسموح',
    deny: 'مرفوض',
    action: 'الإجراء',
    resourceType: 'نوع المورد',
    resourceId: 'معرّف المورد',
    policyVersion: 'نسخة السياسة',
    factsVersion: 'نسخة الحقائق',
    evaluatedAt: 'وقت التقييم',
    decisionIdLabel: 'معرّف القرار',
    plainLanguage: 'الشرح المبسّط',
    reasonCodes: 'أكواد السبب',
    obligations: 'الالتزامات',
    assignments: 'التعيينات',
    policies: 'مراجع السياسات',
    justificationTimeline: 'سلسلة التبرير',
    noneRecorded: 'لا شيء مسجّل.',
    notFound: 'لم يُعثر على القرار.',
    error: 'تعذّر فحص القرار.',
    denied: 'لا يمكن الوصول إلى هذا المحتوى.',
    retry: 'إعادة المحاولة',
  },
  en: {
    inspector: 'Access decision inspector',
    inspectorIntro: 'Enter a decision ID to see its full explanation.',
    technicalNotice:
      'A technical diagnostic screen for administrators — the documented exception to the "user terms, not architect terms" rule (DESIGN-RULES §2.5).',
    decisionId: 'Decision ID',
    inspect: 'Inspect',
    inspecting: 'Inspecting…',
    idle: 'Enter a decision ID to see its explanation.',
    allow: 'Allow',
    deny: 'Deny',
    action: 'Action',
    resourceType: 'Resource type',
    resourceId: 'Resource ID',
    policyVersion: 'Policy version',
    factsVersion: 'Facts version',
    evaluatedAt: 'Evaluated at',
    decisionIdLabel: 'Decision ID',
    plainLanguage: 'Plain-language explanation',
    reasonCodes: 'Reason codes',
    obligations: 'Obligations',
    assignments: 'Assignments',
    policies: 'Policy references',
    justificationTimeline: 'Justification chain',
    noneRecorded: 'None recorded.',
    notFound: 'Decision not found.',
    error: 'Could not inspect the decision.',
    denied: 'This content cannot be accessed.',
    retry: 'Try again',
  },
} as const

export const bootstrapCopy = {
  ar: {
    title: 'التهيئة الأولية',
    intro:
      'يؤسّس هذا الإجراء أول مالك للنظام عند تركيب جديد. يُنفَّذ مرة واحدة في عمر النظام.',
    pendingStatus: 'بانتظار الاكتمال',
    expiresAt: 'تنتهي المهلة في',
    reason: 'سبب الإكمال',
    reasonHint: 'سبب تدقيقي إلزامي. يُحفظ في سجل التدقيق.',
    reasonRequired: 'السبب مطلوب.',
    reasonTooLong: 'السبب يجب ألا يتجاوز ٥٠٠ حرف.',
    complete: 'إكمال التهيئة',
    completing: 'جارٍ الإكمال…',
    confirmTitle: 'إكمال التهيئة الأولية',
    confirmBody:
      'سيُغلق هذا الإجراء نافذة التهيئة نهائياً ولا يمكن التراجع عنه. هل تريد المتابعة؟',
    confirm: 'تأكيد',
    cancel: 'إلغاء',
    versionMissing:
      'تعذّر قراءة نسخة الحالة. حدّث الصفحة وحاول مجدداً.',
    saved: 'اكتملت التهيئة.',
  },
  en: {
    title: 'Initial bootstrap',
    intro:
      'This establishes the first system owner on a fresh install. It runs once in the lifetime of the system.',
    pendingStatus: 'Awaiting completion',
    expiresAt: 'Expires at',
    reason: 'Completion reason',
    reasonHint: 'A mandatory audited reason. Stored in the audit trail.',
    reasonRequired: 'A reason is required.',
    reasonTooLong: 'The reason must not exceed 500 characters.',
    complete: 'Complete bootstrap',
    completing: 'Completing…',
    confirmTitle: 'Complete the initial bootstrap',
    confirmBody:
      'This permanently closes the bootstrap window and cannot be undone. Continue?',
    confirm: 'Confirm',
    cancel: 'Cancel',
    versionMissing:
      'The state version could not be read. Refresh the page and try again.',
    saved: 'Bootstrap completed.',
  },
} as const
