export const accountsCopy = {
  ar: {
    title: 'الحسابات والصلاحيات',
    intro: 'أدر حسابات الدخول والأدوار وافحص قرارات الوصول.',
    tabsLabel: 'مساحات الحسابات والصلاحيات',
    tabAccounts: 'الحسابات',
    tabRoles: 'الأدوار',
    tabDiagnostics: 'تشخيص الوصول',
    tabBootstrap: 'التهيئة',
    unavailable: 'غير متاح',
    unavailableBody: 'لا تملك الصلاحية المطلوبة لعرض هذا القسم.',
    retry: 'إعادة المحاولة',
    loading: 'جارٍ التحميل…',
    close: 'إغلاق',
    save: 'حفظ',
    cancel: 'إلغاء',
    done: 'تم تنفيذ الإجراء.',
    saveError: 'لم يُحفظ التغيير. أعد المحاولة.',
    stale: 'تغيّرت البيانات من مكان آخر. حدّث القائمة وأعد المحاولة.',
  },
  en: {
    title: 'Accounts & Permissions',
    intro: 'Manage sign-in accounts, roles, and inspect access decisions.',
    tabsLabel: 'Accounts & permissions workspaces',
    tabAccounts: 'Accounts',
    tabRoles: 'Roles',
    tabDiagnostics: 'Access diagnostics',
    tabBootstrap: 'Bootstrap',
    unavailable: 'Unavailable',
    unavailableBody:
      'You do not have the required permission to view this section.',
    retry: 'Retry',
    loading: 'Loading…',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    done: 'Action completed.',
    saveError: 'The change was not saved. Try again.',
    stale: 'This data changed elsewhere. Refresh the list and try again.',
  },
} as const

export const accountCopy = {
  ar: {
    accounts: 'حسابات الدخول',
    noAccounts: 'لا توجد حسابات دخول بعد.',
    noAccountsBody: 'ابدأ بإنشاء حساب لموظف حتى يتمكن من تسجيل الدخول.',
    employee: 'الموظف',
    username: 'اسم الدخول',
    status: 'الحالة',
    actions: 'الإجراءات',
    manage: 'إدارة',
    manageAccount: 'إدارة الحساب',
    addAccount: 'إضافة حساب',
    addAccountTitle: 'إضافة حساب دخول',
    addAccountIntro:
      'اختر الموظف واكتب اسم الدخول. يُنشأ الحساب بانتظار التفعيل.',
    backToAccounts: 'عودة إلى الحسابات',
    managePageIntro: 'استعرض حالة الحساب ونفّذ الإجراءات المتاحة عليه.',
    create: 'إنشاء الحساب',
    saving: 'جارٍ الحفظ…',
    usernameHint: '٣ أحرف فأكثر: حروف إنجليزية وأرقام و . _ - فقط.',
    validation: 'اختر موظفاً واكتب اسم دخول صحيحاً.',
    peopleError: 'تعذّر تحميل قائمة الموظفين.',
    reason: 'سبب الإجراء (اختياري)',
    reasonHint: 'يُحفظ في سجل التدقيق ليُعرف لاحقاً سبب التغيير.',
    pending: 'بانتظار التفعيل',
    active: 'نشط',
    locked: 'مقفل',
    disabled: 'معطَّل',
    archived: 'مؤرشف',
    mustChangePassword: 'مطلوب من الموظف تغيير كلمة المرور عند الدخول القادم.',
    activate: 'تفعيل الحساب',
    unlock: 'فك القفل',
    disable: 'تعطيل الحساب',
    archive: 'أرشفة الحساب',
    revokeSessions: 'إنهاء الجلسات المفتوحة',
    forcePasswordChange: 'إلزامه بتغيير كلمة المرور',
    noActions: 'لا توجد إجراءات متاحة على هذا الحساب.',
    activateHint: 'يعيد للموظف القدرة على تسجيل الدخول.',
    unlockHint: 'يلغي القفل الناتج عن محاولات الدخول الفاشلة.',
    disableHint: 'يمنع الدخول مؤقتاً مع الاحتفاظ بالحساب.',
    archiveHint: 'إغلاق نهائي للحساب. لا يمكن التراجع.',
    revokeSessionsHint: 'يخرج الموظف من كل الأجهزة فوراً.',
    forcePasswordChangeHint: 'يطلب منه كلمة مرور جديدة عند الدخول القادم.',
    activationIssued: 'تم إصدار رمز التفعيل',
    activationControlledDelivery:
      'يُسلَّم الرمز للموظف عبر القناة الآمنة المخصصة ولا يُعرض في هذه الشاشة أبداً.',
    activationExpiryLabel: 'تنتهي صلاحية الرمز في',
    activationDismiss: 'تم',
    activationFailed: 'تعذّر إصدار رمز التفعيل. أعد المحاولة.',
    accountsError: 'تعذّر تحميل الحسابات.',
    saveError: 'لم يُحفظ التغيير. أعد المحاولة.',
    peopleLoading: 'جارٍ تحميل الموظفين…',
    peopleEmpty: 'لا يوجد موظفون متاحون لإضافة حساب لهم.',
    peoplePickerPlaceholder: 'ابحث عن الموظف أو اختره…',
    peoplePickerLabel: 'قائمة الموظفين',
    peoplePickerEmpty: 'لا يطابق البحث أي موظف.',
    peoplePickerDenied: 'لا يمكن الوصول إلى قائمة الموظفين.',
    peopleLoadMore: 'تحميل المزيد',
  },
  en: {
    accounts: 'Sign-in accounts',
    noAccounts: 'No sign-in accounts yet.',
    noAccountsBody: 'Start by creating an account so an employee can sign in.',
    employee: 'Employee',
    username: 'Username',
    status: 'Status',
    actions: 'Actions',
    manage: 'Manage',
    manageAccount: 'Manage account',
    addAccount: 'Add account',
    addAccountTitle: 'Add a sign-in account',
    addAccountIntro:
      'Pick the employee and choose a username. The account starts as awaiting activation.',
    backToAccounts: 'Back to accounts',
    managePageIntro: 'Review the account state and run its available actions.',
    create: 'Create account',
    saving: 'Saving…',
    usernameHint: 'At least 3 characters: letters, digits, and . _ - only.',
    validation: 'Select an employee and enter a valid username.',
    peopleError: 'Could not load the employee list.',
    reason: 'Reason (optional)',
    reasonHint:
      'Stored in the audit trail so the change can be explained later.',
    pending: 'Awaiting activation',
    active: 'Active',
    locked: 'Locked',
    disabled: 'Disabled',
    archived: 'Archived',
    mustChangePassword: 'The employee must set a new password at next sign-in.',
    activate: 'Activate account',
    unlock: 'Unlock',
    disable: 'Disable account',
    archive: 'Archive account',
    revokeSessions: 'End open sessions',
    forcePasswordChange: 'Require a password change',
    noActions: 'No actions are available on this account.',
    activateHint: 'Restores the employee’s ability to sign in.',
    unlockHint: 'Clears the lock caused by failed sign-in attempts.',
    disableHint: 'Blocks sign-in temporarily while keeping the account.',
    archiveHint: 'Closes the account for good. This cannot be undone.',
    revokeSessionsHint: 'Signs the employee out of every device immediately.',
    forcePasswordChangeHint: 'Asks for a new password at their next sign-in.',
    activationIssued: 'Activation issued',
    activationControlledDelivery:
      'The activation secret is delivered to the employee through the controlled secure channel and is never shown on this screen.',
    activationExpiryLabel: 'The activation expires at',
    activationDismiss: 'Done',
    activationFailed: 'The activation could not be issued. Try again.',
    accountsError: 'Accounts could not be loaded.',
    saveError: 'The change was not saved. Try again.',
    peopleLoading: 'Loading employees…',
    peopleEmpty: 'No employees are available to attach an account to.',
    peoplePickerPlaceholder: 'Search or pick an employee…',
    peoplePickerLabel: 'Employees',
    peoplePickerEmpty: 'No employees match your search.',
    peoplePickerDenied: 'The employee list cannot be accessed.',
    peopleLoadMore: 'Load more',
  },
} as const

/*
 * Bilingual action label map for the capability catalog. The wire's
 * `action` is the last dotted segment of a capability code (e.g. `read`,
 * `manage`); the table renders a human-readable verb in the active locale
 * and keeps the raw value as a fallback so unknown verbs are never
 * hidden from the operator.
 */
export const CAPABILITY_ACTION_LABELS: Record<string, { ar: string; en: string }> = {
  create: { ar: 'إنشاء', en: 'Create' },
  read: { ar: 'قراءة', en: 'Read' },
  list: { ar: 'إدراج', en: 'List' },
  update: { ar: 'تعديل', en: 'Update' },
  delete: { ar: 'حذف', en: 'Delete' },
  submit: { ar: 'تقديم', en: 'Submit' },
  return: { ar: 'إرجاع', en: 'Return' },
  complete: { ar: 'إكمال', en: 'Complete' },
  query: { ar: 'بحث', en: 'Query' },
  request: { ar: 'طلب', en: 'Request' },
  confirm: { ar: 'تأكيد', en: 'Confirm' },
  cancel: { ar: 'إلغاء', en: 'Cancel' },
  archive: { ar: 'أرشفة', en: 'Archive' },
  publish: { ar: 'نشر', en: 'Publish' },
  retire: { ar: 'سحب', en: 'Retire' },
  manage: { ar: 'إدارة', en: 'Manage' },
  author: { ar: 'تأليف', en: 'Author' },
  approve: { ar: 'اعتماد', en: 'Approve' },
  decide: { ar: 'اتخاذ قرار', en: 'Decide' },
  reassign: { ar: 'إعادة تعيين', en: 'Reassign' },
  escalate: { ar: 'تصعيد', en: 'Escalate' },
  'initiate-upload': { ar: 'بدء رفع', en: 'Initiate upload' },
  'complete-upload': { ar: 'إكمال رفع', en: 'Complete upload' },
  'get-upload-status': { ar: 'حالة الرفع', en: 'Upload status' },
  'scan-version': { ar: 'فحص النسخة', en: 'Scan version' },
  'reconcile-promotion': { ar: 'مطابقة ترقية', en: 'Reconcile promotion' },
  link: { ar: 'ربط', en: 'Link' },
  download: { ar: 'تنزيل', en: 'Download' },
  hold: { ar: 'تعليق', en: 'Hold' },
  grant: { ar: 'منح', en: 'Grant' },
  run: { ar: 'تنفيذ', en: 'Run' },
  export: { ar: 'تصدير', en: 'Export' },
  dashboard: { ar: 'لوحة', en: 'Dashboard' },
  reference: { ar: 'مرجع', en: 'Reference' },
  assign: { ar: 'تعيين', en: 'Assign' },
  start: { ar: 'بدء', en: 'Start' },
  comment: { ar: 'تعليق', en: 'Comment' },
  'participant-manage': { ar: 'إدارة المشاركين', en: 'Manage participants' },
  verify: { ar: 'تحقق', en: 'Verify' },
  evaluate: { ar: 'تقييم', en: 'Evaluate' },
  accept: { ar: 'قبول', en: 'Accept' },
  assess: { ar: 'تقييم', en: 'Assess' },
  impact: { ar: 'أثر', en: 'Impact' },
  override_official_holiday: { ar: 'تجاوز عطلة رسمية', en: 'Override official holiday' },
  restore: { ar: 'استعادة', en: 'Restore' },
  logs: { ar: 'سجلات', en: 'Logs' },
  alerts: { ar: 'تنبيهات', en: 'Alerts' },
  maintenance: { ar: 'صيانة', en: 'Maintenance' },
}

/*
 * Bilingual module label map for the capability catalog. The wire's
 * `module_code` is the first dotted segment of a capability code
 * (e.g. `tasks`, `identity`); the table renders the localized
 * area name in the primary line and the raw module_code as a
 * technical secondary line so the canonical identifier stays visible.
 */
export const CAPABILITY_MODULE_LABELS: Record<string, { ar: string; en: string }> = {
  tasks: { ar: 'المهام', en: 'Tasks' },
  documents: { ar: 'المستندات', en: 'Documents' },
  search: { ar: 'البحث', en: 'Search' },
  reporting: { ar: 'التقارير', en: 'Reporting' },
  notifications: { ar: 'الإشعارات', en: 'Notifications' },
  identity: { ar: 'الهوية والحسابات', en: 'Identity & accounts' },
  organization: { ar: 'المنظمة', en: 'Organization' },
  authorization: { ar: 'الصلاحيات', en: 'Authorization' },
  audit: { ar: 'التدقيق', en: 'Audit' },
  strategy: { ar: 'الاستراتيجية', en: 'Strategy' },
  portfolio_projects: { ar: 'المحافظ والمشاريع', en: 'Portfolios & projects' },
  risk: { ar: 'المخاطر', en: 'Risk' },
  platform_settings: { ar: 'إعدادات المنصة', en: 'Platform settings' },
  platform_operations: { ar: 'عمليات المنصة', en: 'Platform operations' },
}

/*
 * Bilingual human-readable label for every capability in the canonical
 * catalog (Modules/Authorization/Contracts/CapabilityCatalog.php), keyed
 * by the full dotted code. The role form renders these as the primary
 * line so the operator reads a meaningful permission name instead of a
 * technical identifier; the canonical code stays available as a mono
 * secondary line in the English locale and as a search/keyboard target
 * in both. An unknown code falls back to the raw value so nothing is
 * ever hidden from the operator.
 */
export const CAPABILITY_LABELS: Record<string, { ar: string; en: string }> = {
  'tasks.create': { ar: 'إنشاء مهمة', en: 'Create task' },
  'tasks.read': { ar: 'قراءة مهمة', en: 'Read task' },
  'tasks.list': { ar: 'إدراج المهام', en: 'List tasks' },
  'tasks.update': { ar: 'تعديل مهمة', en: 'Update task' },
  'tasks.assign': { ar: 'تعيين مهمة', en: 'Assign task' },
  'tasks.start': { ar: 'بدء مهمة', en: 'Start task' },
  'tasks.complete': { ar: 'إكمال مهمة', en: 'Complete task' },
  'tasks.cancel': { ar: 'إلغاء مهمة', en: 'Cancel task' },
  'tasks.comment': { ar: 'التعليق على مهمة', en: 'Comment on task' },
  'tasks.participant-manage': { ar: 'إدارة مشاركي المهمة', en: 'Manage task participants' },
  'documents.create': { ar: 'إنشاء مستند', en: 'Create document' },
  'documents.update': { ar: 'تعديل مستند', en: 'Update document' },
  'documents.read': { ar: 'قراءة مستند', en: 'Read document' },
  'documents.list': { ar: 'إدراج المستندات', en: 'List documents' },
  'documents.initiate-upload': { ar: 'بدء رفع مستند', en: 'Initiate document upload' },
  'documents.complete-upload': { ar: 'إكمال رفع مستند', en: 'Complete document upload' },
  'documents.get-upload-status': { ar: 'الاستعلام عن حالة الرفع', en: 'Get upload status' },
  'documents.scan-version': { ar: 'فحص نسخة المستند', en: 'Scan document version' },
  'documents.reconcile-promotion': { ar: 'مطابقة ترقية النسخة', en: 'Reconcile version promotion' },
  'documents.link': { ar: 'ربط مستند', en: 'Link document' },
  'documents.download': { ar: 'تنزيل مستند', en: 'Download document' },
  'documents.archive': { ar: 'أرشفة مستند', en: 'Archive document' },
  'documents.hold': { ar: 'تعليق مستند', en: 'Hold document' },
  'documents.grant': { ar: 'منح وصول لمستند', en: 'Grant document access' },
  'search.query': { ar: 'البحث', en: 'Search' },
  'reporting.read': { ar: 'قراءة التقارير', en: 'Read reports' },
  'reporting.list': { ar: 'إدراج التقارير', en: 'List reports' },
  'reporting.run': { ar: 'تشغيل تقرير', en: 'Run report' },
  'reporting.export': { ar: 'تصدير تقرير', en: 'Export report' },
  'reporting.download': { ar: 'تنزيل تصدير تقرير', en: 'Download report export' },
  'reporting.dashboard': { ar: 'عرض لوحات المعلومات', en: 'View dashboards' },
  'notifications.read': { ar: 'قراءة الإشعارات', en: 'Read notifications' },
  'notifications.manage': { ar: 'إدارة الإشعارات', en: 'Manage notifications' },
  'identity.account.read': { ar: 'قراءة حسابات الدخول', en: 'Read sign-in accounts' },
  'identity.account.manage': { ar: 'إدارة حسابات الدخول', en: 'Manage sign-in accounts' },
  'organization.cluster.manage': { ar: 'إدارة المجمّع', en: 'Manage the cluster' },
  'organization.cluster.read': { ar: 'قراءة المجمّع', en: 'Read the cluster' },
  'organization.facility.manage': { ar: 'إدارة المنشآت', en: 'Manage facilities' },
  'organization.facility.read': { ar: 'قراءة المنشآت', en: 'Read facilities' },
  'organization.unit.manage': { ar: 'إدارة الوحدات', en: 'Manage units' },
  'organization.unit.read': { ar: 'قراءة الوحدات', en: 'Read units' },
  'organization.position.manage': { ar: 'إدارة الوظائف', en: 'Manage positions' },
  'organization.position.read': { ar: 'قراءة الوظائف', en: 'Read positions' },
  'organization.person.manage': { ar: 'إدارة الموظفين', en: 'Manage employees' },
  'organization.person.read': { ar: 'قراءة بيانات الموظفين', en: 'Read employee data' },
  'organization.person.reference': { ar: 'التحقق من مرجع الموظف', en: 'Validate employee reference' },
  'organization.assignment.manage': { ar: 'إدارة التكليفات', en: 'Manage assignments' },
  'organization.assignment.read': { ar: 'قراءة التكليفات', en: 'Read assignments' },
  'organization.import.manage': { ar: 'إدارة استيراد الموظفين', en: 'Manage employee imports' },
  'organization.import.approve': { ar: 'اعتماد استيراد الموظفين', en: 'Approve employee imports' },
  'organization.import.read': { ar: 'قراءة عمليات الاستيراد', en: 'Read import jobs' },
  'organization.temporary-assignment.manage': { ar: 'إدارة التكليفات المؤقتة', en: 'Manage temporary assignments' },
  'organization.temporary-assignment.read': { ar: 'قراءة التكليفات المؤقتة', en: 'Read temporary assignments' },
  'authorization.role.read': { ar: 'قراءة الأدوار', en: 'Read roles' },
  'authorization.role.manage': { ar: 'إدارة الأدوار', en: 'Manage roles' },
  'authorization.capability.read': { ar: 'قراءة القدرات', en: 'Read capabilities' },
  'authorization.capability.manage': { ar: 'إدارة القدرات', en: 'Manage capabilities' },
  'authorization.assignment.read': { ar: 'قراءة تعيينات الأدوار', en: 'Read role assignments' },
  'authorization.assignment.manage': { ar: 'إدارة تعيينات الأدوار', en: 'Manage role assignments' },
  'authorization.delegation.read': { ar: 'قراءة التفويضات', en: 'Read delegations' },
  'authorization.delegation.manage': { ar: 'إدارة التفويضات', en: 'Manage delegations' },
  'authorization.deny.read': { ar: 'قراءة الاستثناءات الصريحة', en: 'Read explicit denies' },
  'authorization.deny.manage': { ar: 'إدارة الاستثناءات الصريحة', en: 'Manage explicit denies' },
  'authorization.policy.read': { ar: 'قراءة سياسات التصنيف', en: 'Read classification policies' },
  'authorization.policy.manage': { ar: 'إدارة سياسات التصنيف', en: 'Manage classification policies' },
  'authorization.audit.read': { ar: 'قراءة سجل تدقيق الصلاحيات', en: 'Read authorization audit' },
  'authorization.decision.read': { ar: 'تشخيص قرارات الوصول', en: 'Inspect access decisions' },
  'audit.event.read': { ar: 'قراءة أحداث التدقيق', en: 'Read audit events' },
  'audit.event.export': { ar: 'تصدير أحداث التدقيق', en: 'Export audit events' },
  'audit.integrity.verify': { ar: 'التحقق من سلامة السجل', en: 'Verify audit integrity' },
  'strategy.plan.read': { ar: 'قراءة الخطط الاستراتيجية', en: 'Read strategy plans' },
  'strategy.plan.manage': { ar: 'إدارة الخطط الاستراتيجية', en: 'Manage strategy plans' },
  'strategy.indicator.read': { ar: 'قراءة المؤشرات', en: 'Read indicators' },
  'strategy.indicator.manage': { ar: 'إدارة المؤشرات', en: 'Manage indicators' },
  'strategy.measurement.submit': { ar: 'تقديم قياسات', en: 'Submit measurements' },
  'strategy.measurement.approve': { ar: 'اعتماد قياسات', en: 'Approve measurements' },
  'strategy.impact.read': { ar: 'قراءة تقييم الأثر', en: 'Read impact assessments' },
  'portfolio_projects.portfolio.read': { ar: 'قراءة المحافظ', en: 'Read portfolios' },
  'portfolio_projects.portfolio.manage': { ar: 'إدارة المحافظ', en: 'Manage portfolios' },
  'portfolio_projects.project.read': { ar: 'قراءة المشاريع', en: 'Read projects' },
  'portfolio_projects.project.manage': { ar: 'إدارة المشاريع', en: 'Manage projects' },
  'portfolio_projects.milestone.approve': { ar: 'اعتماد مراحل المشروع', en: 'Approve project milestones' },
  'portfolio_projects.impact.submit': { ar: 'تقديم تقييم الأثر', en: 'Submit impact assessments' },
  'portfolio_projects.budget.read': { ar: 'قراءة الميزانيات', en: 'Read budgets' },
  'risk.risk.read': { ar: 'قراءة المخاطر', en: 'Read risks' },
  'risk.risk.manage': { ar: 'إدارة المخاطر', en: 'Manage risks' },
  'risk.assess': { ar: 'تقييم المخاطر', en: 'Assess risks' },
  'risk.control.manage': { ar: 'إدارة الضوابط', en: 'Manage controls' },
  'risk.treatment.manage': { ar: 'إدارة خطط المعالجة', en: 'Manage risk treatments' },
  'risk.accept': { ar: 'قبول المخاطر', en: 'Accept risks' },
  'risk.kri.manage': { ar: 'إدارة مؤشرات المخاطر الرئيسية', en: 'Manage KRIs' },
  'platform_settings.read': { ar: 'قراءة إعدادات المنصة', en: 'Read platform settings' },
  'platform_settings.manage': { ar: 'إدارة إعدادات المنصة', en: 'Manage platform settings' },
  'platform_settings.publish': { ar: 'نشر إعدادات المنصة', en: 'Publish platform settings' },
  'platform_settings.calendar.read': { ar: 'قراءة التقويم الرسمي', en: 'Read the official calendar' },
  'platform_settings.calendar.manage': { ar: 'إدارة التقويم الرسمي', en: 'Manage the official calendar' },
  'platform_settings.calendar.override_official_holiday': { ar: 'تجاوز عطلة رسمية', en: 'Override an official holiday' },
  'platform_operations.health.read': { ar: 'قراءة حالة المنصة', en: 'Read platform health' },
  'platform_operations.backup.read': { ar: 'قراءة النسخ الاحتياطية', en: 'Read backups' },
  'platform_operations.backup.run': { ar: 'تشغيل نسخة احتياطية', en: 'Run a backup' },
  'platform_operations.restore.request': { ar: 'طلب استعادة', en: 'Request a restore' },
  'platform_operations.restore.confirm': { ar: 'تأكيد استعادة', en: 'Confirm a restore' },
  'platform_operations.logs.read': { ar: 'قراءة سجلات المنصة', en: 'Read platform logs' },
  'platform_operations.logs.restore': { ar: 'استعادة السجلات', en: 'Restore logs' },
  'platform_operations.alerts.manage': { ar: 'إدارة التنبيهات', en: 'Manage alerts' },
  'platform_operations.maintenance.manage': { ar: 'إدارة نوافذ الصيانة', en: 'Manage maintenance windows' },
  'platform_operations.maintenance.cancel': { ar: 'إلغاء نافذة صيانة', en: 'Cancel a maintenance window' },
}

export const roleCopy = {
  ar: {
    roles: 'الأدوار والصلاحيات',
    resourceRoles: 'الأدوار',
    resourceCapabilities: 'القدرات',
    resourceAssignments: 'التعيينات',
    resourcesToolbar: 'أدوار وقدرات وتعيينات',
    code: 'رمز الدور',
    name: 'اسم الدور',
     capabilities: 'الصلاحيات',
     capabilityCatalogIntro: 'اختر الصلاحيات التي يملكها هذا الدور.',
     roleReviewHeading: 'مراجعة الدور',
     selectedCount: 'المحددة',
     visibleCount: 'الظاهرة',
     reviewNotAvailable: 'غير متاح',

    create: 'إنشاء دور',
    save: 'حفظ التغييرات',
    edit: 'تعديل',
    archive: 'أرشفة',
    clone: 'نسخ كدور مخصص',
    revoke: 'إزالة',
    expire: 'إنهاء',
    cancel: 'إلغاء',
    saving: 'جارٍ الحفظ…',
    empty: 'لا توجد أدوار لعرضها.',
    noCatalog:
      'لا تتوفر قائمة الصلاحيات (تحتاج authorization.capability.read).',
    roleError: 'تعذّر حفظ الدور.',
    rolesError: 'تعذّر تحميل الأدوار.',
    countCapabilities: 'صلاحية',
    systemRole: 'نظامي',
    customRole: 'مخصص',
    createRoleTitle: 'إنشاء دور',
    editRoleTitle: 'تعديل الدور',
    roleSheetIntro: 'الاسم والرمز والصلاحيات الممنوحة للدور.',
    roleInfo: 'معلومات الدور',
    backToRoles: 'عودة إلى الأدوار',
    createPageIntro: 'عرّف الدور واختر صلاحياته.',
    editPageIntro: 'حدّث اسم الدور وصلاحياته.',
    capabilitySearchLabel: 'بحث الصلاحيات',
    capabilitySearchPlaceholder: 'ابحث بالرمز أو المجال أو الوصف…',
    capabilitySearchEmpty: 'لا توجد صلاحيات مطابقة للبحث.',
    capabilityCatalogError: 'تعذّر تحميل قائمة الصلاحيات كاملة.',
    capabilityRetry: 'أعد المحاولة',
    selected: 'محددة',
    selectGroup: 'تحديد المجموعة',
    clearGroup: 'إلغاء تحديد المجموعة',
    createSubmit: 'أنشئ الدور',
    backToAssignments: 'عودة إلى التعيينات',
    codeHint: 'حروف إنجليزية صغيرة وأرقام ونقاط وشرطات سفلية.',
    createError: 'تعذّر إنشاء الدور.',
    updateError: 'تعذّر تحديث الدور.',
    archiveTitle: 'أرشفة الدور',
    archiveBody: 'سيُؤرشف الدور ولن يعود قابلاً للاستخدام. هذا الإجراء نهائي.',
    confirm: 'تأكيد',
    capabilitiesEmpty: 'لا توجد قدرات لعرضها.',
    capabilityColumnPermission: 'الصلاحية',
    capabilityColumnArea: 'المجال',
    capabilityColumnSensitivity: 'الحساسية',
    capabilityGroup: 'المجموعة',
    capabilityCodeHint: 'الرمز التقني للقدرة كما يُستخدم في الـAPI.',
    capabilityGroupHint: 'مجموعة تنظيمية إضافية للقدرة، تُعرض عند اختلافها عن المجال.',
    sensitivityNormal: 'عادية',
    sensitivitySensitive: 'حساسة',
    sensitivityCritical: 'حرجة',
    sensitivityPublic: 'عام',
    sensitivityInternal: 'داخلي',
    sensitivityConfidential: 'سري',
    sensitivityTopSecret: 'سري للغاية',
    sensitiveCapability: 'قدرة حساسة',
    subject: 'المستخدم',
    assignmentRole: 'الدور',
    assignmentScope: 'النطاق',
    assignmentStatus: 'الحالة',
    assignmentWindow: 'الفترة',
    addAssignment: 'إضافة تعيين',
    addAssignmentTitle: 'إضافة تعيين دور',
     assignmentIntro: 'منح دور لمستخدم في نطاق محدد.',
     assignmentDetailsHeading: 'تفاصيل التعيين',
     assignmentWindowHeading: 'الفترة الزمنية',
     assignmentReviewHeading: 'مراجعة التعيين',
     assignmentNotSelected: 'لم يُحدّد بعد',
     assignmentOpenEnded: 'مفتوح النهاية',

    assignmentAccount: 'الحساب',
    assignmentRoleLabel: 'الدور',
    assignmentScopeTypeLabel: 'نوع النطاق',
    assignmentScopeTargetLabel: 'النطاق',
    assignmentStartLabel: 'البداية',
    assignmentEndLabel: 'النهاية',
    assignmentStartHint: 'مطلوب. يُفعَّل التعيين عند بدايته.',
    assignmentEndHint: 'اختياري. يُنهى التعيين عند نهايته.',
    assignmentStartRequired: 'البداية مطلوبة.',
    assignmentWindowInvalid: 'يجب أن تكون النهاية بعد البداية.',
    assignmentCreate: 'إنشاء التعيين',
    assignmentError: 'تعذّر حفظ التعيين.',
    assignmentValidation: 'اختر الحساب والدور والنطاق.',
    assignmentAccountMissing: 'لا توجد حسابات متاحة.',
    assignmentRoleMissing: 'لا توجد أدوار نشطة.',
    assignmentAccountPickerPlaceholder: 'ابحث عن الحساب أو اختره…',
    assignmentAccountPickerLabel: 'قائمة الحسابات',
    assignmentAccountPickerEmpty: 'لا يطابق البحث أي حساب.',
    assignmentAccountPickerDenied: 'لا يمكن الوصول إلى قائمة الحسابات.',
    assignmentAccountPickerError: 'تعذّر تحميل الحسابات.',
    assignmentAccountPickerLoading: 'جارٍ تحميل الحسابات…',
    assignmentAccountLoadMore: 'تحميل المزيد من الحسابات',
    assignmentRolePickerPlaceholder: 'ابحث عن الدور أو اختره…',
    assignmentRolePickerLabel: 'قائمة الأدوار',
    assignmentRolePickerEmpty: 'لا يطابق البحث أي دور.',
    assignmentRolePickerDenied: 'لا يمكن الوصول إلى قائمة الأدوار.',
    assignmentRolePickerError: 'تعذّر تحميل الأدوار.',
    assignmentRolePickerLoading: 'جارٍ تحميل الأدوار…',
    assignmentRoleLoadMore: 'تحميل المزيد من الأدوار',
    assignmentActivate: 'تفعيل',
    assignmentActivateTitle: 'تفعيل التعيين',
    assignmentActivateBody: 'سيُفعَّل التعيين فوراً ويُمنح المستخدم صلاحية الدور.',
    assignmentExpireTitle: 'إنهاء التعيين',
    assignmentExpireBody: 'سيُنهى التعيين فوراً وتُسحب الصلاحية.',
    assignmentRevokeTitle: 'إزالة التعيين',
    assignmentRevokeBody: 'ستُزال صلاحية الدور من المستخدم نهائياً.',
    assignmentsEmpty: 'لا توجد تعيينات لعرضها.',
    scopeCluster: 'المجموعة',
    scopeFacility: 'المنشأة',
    scopeUnit: 'الوحدة',
    scopeSearchLabel: 'ابحث عن النطاق',
    scopeSearchPlaceholder: 'اكتب للبحث عن النطاق…',
    scopeSelectPlaceholder: 'اختر النطاق',
    scopeNoResults: 'لا توجد نطاقات مطابقة.',
    scopeSearching: 'جارٍ البحث عن النطاقات…',
    scopeSearchError: 'تعذّر البحث عن النطاقات.',
    scopeSearchDenied: 'لا يمكن الوصول إلى هذا المحتوى.',
    unavailable: 'غير متاح',
    effectivePending: 'بانتظار التفعيل',
    effectiveActive: 'نشط',
    effectiveExpired: 'منتهٍ',
    effectiveRevoked: 'مُزال',
  },
  en: {
    roles: 'Roles & Permissions',
    resourceRoles: 'Roles',
    resourceCapabilities: 'Capabilities',
    resourceAssignments: 'Assignments',
    resourcesToolbar: 'Roles, capabilities and assignments',
    code: 'Role code',
    name: 'Role name',
     capabilities: 'Capabilities',
     capabilityCatalogIntro: 'Choose the permissions this role should grant.',
     roleReviewHeading: 'Role review',
     selectedCount: 'Selected',
     visibleCount: 'Visible',
     reviewNotAvailable: 'Not available',

    create: 'Create role',
    save: 'Save changes',
    edit: 'Edit',
    archive: 'Archive',
    clone: 'Clone as custom role',
    revoke: 'Remove',
    expire: 'Expire',
    cancel: 'Cancel',
    saving: 'Saving…',
    empty: 'No roles to display.',
    noCatalog:
      'Capability catalog unavailable (needs authorization.capability.read).',
    roleError: 'Could not save the role.',
    rolesError: 'Roles could not be loaded.',
    countCapabilities: 'capabilities',
    systemRole: 'System',
    customRole: 'Custom',
    createRoleTitle: 'Create role',
    editRoleTitle: 'Edit role',
    roleSheetIntro: 'The name, code, and permissions granted to the role.',
    roleInfo: 'Role details',
    backToRoles: 'Back to roles',
    createPageIntro: 'Define the role and pick its capabilities.',
    editPageIntro: 'Update the role name and capabilities.',
    capabilitySearchLabel: 'Search capabilities',
    capabilitySearchPlaceholder: 'Search by code, area, or description…',
    capabilitySearchEmpty: 'No capabilities match your search.',
    capabilityCatalogError: 'The full capability catalog could not be loaded.',
    capabilityRetry: 'Try again',
    selected: 'selected',
    selectGroup: 'Select group',
    clearGroup: 'Clear group',
    createSubmit: 'Create role',
    backToAssignments: 'Back to assignments',
    codeHint: 'Lowercase letters, digits, dots, and underscores.',
    createError: 'Could not create the role.',
    updateError: 'Could not update the role.',
    archiveTitle: 'Archive role',
    archiveBody: 'The role will be archived and can no longer be used. This cannot be undone.',
    confirm: 'Confirm',
    capabilitiesEmpty: 'No capabilities to display.',
    capabilityColumnPermission: 'Permission',
    capabilityColumnArea: 'Area',
    capabilityColumnSensitivity: 'Sensitivity',
    capabilityGroup: 'Group',
    capabilityCodeHint: 'The canonical API identifier for the capability.',
    capabilityGroupHint: 'An additional organizational grouping shown only when it differs from the area.',
    sensitivityNormal: 'Normal',
    sensitivitySensitive: 'Sensitive',
    sensitivityCritical: 'Critical',
    sensitivityPublic: 'Public',
    sensitivityInternal: 'Internal',
    sensitivityConfidential: 'Confidential',
    sensitivityTopSecret: 'Top secret',
    sensitiveCapability: 'Sensitive capability',
    subject: 'User',
    assignmentRole: 'Role',
    assignmentScope: 'Scope',
    assignmentStatus: 'Status',
    assignmentWindow: 'Period',
    addAssignment: 'Add assignment',
    addAssignmentTitle: 'Add role assignment',
     assignmentIntro: 'Grant a role to a user within a specific scope.',
     assignmentDetailsHeading: 'Assignment details',
     assignmentWindowHeading: 'Effective date window',
     assignmentReviewHeading: 'Assignment review',
     assignmentNotSelected: 'Not selected',
     assignmentOpenEnded: 'Open-ended',

    assignmentAccount: 'Account',
    assignmentRoleLabel: 'Role',
    assignmentScopeTypeLabel: 'Scope type',
    assignmentScopeTargetLabel: 'Scope',
    assignmentStartLabel: 'Start',
    assignmentEndLabel: 'End',
    assignmentStartHint: 'Required. The assignment activates at its start.',
    assignmentEndHint: 'Optional. The assignment expires at its end.',
    assignmentStartRequired: 'Start is required.',
    assignmentWindowInvalid: 'The end must be strictly after the start.',
    assignmentCreate: 'Create assignment',
    assignmentError: 'Could not save the assignment.',
    assignmentValidation: 'Select the account, role, and scope.',
    assignmentAccountMissing: 'No accounts available.',
    assignmentRoleMissing: 'No active roles.',
    assignmentAccountPickerPlaceholder: 'Search or pick an account…',
    assignmentAccountPickerLabel: 'Accounts',
    assignmentAccountPickerEmpty: 'No accounts match your search.',
    assignmentAccountPickerDenied: 'The account list cannot be accessed.',
    assignmentAccountPickerError: 'Accounts could not be loaded.',
    assignmentAccountPickerLoading: 'Loading accounts…',
    assignmentAccountLoadMore: 'Load more accounts',
    assignmentRolePickerPlaceholder: 'Search or pick a role…',
    assignmentRolePickerLabel: 'Roles',
    assignmentRolePickerEmpty: 'No roles match your search.',
    assignmentRolePickerDenied: 'The role list cannot be accessed.',
    assignmentRolePickerError: 'Roles could not be loaded.',
    assignmentRolePickerLoading: 'Loading roles…',
    assignmentRoleLoadMore: 'Load more roles',
    assignmentActivate: 'Activate',
    assignmentActivateTitle: 'Activate assignment',
    assignmentActivateBody: 'The assignment will activate immediately and the user is granted the role permission.',
    assignmentExpireTitle: 'Expire assignment',
    assignmentExpireBody: 'The assignment will expire immediately and the permission is withdrawn.',
    assignmentRevokeTitle: 'Remove assignment',
    assignmentRevokeBody: 'The role permission will be permanently removed from the user.',
    assignmentsEmpty: 'No assignments to display.',
    scopeCluster: 'Cluster',
    scopeFacility: 'Facility',
    scopeUnit: 'Unit',
    scopeSearchLabel: 'Search for a scope',
    scopeSearchPlaceholder: 'Type to search for a scope…',
    scopeSelectPlaceholder: 'Select a scope',
    scopeNoResults: 'No matching scopes.',
    scopeSearching: 'Searching for scopes…',
    scopeSearchError: 'Scope search failed.',
    scopeSearchDenied: 'This content cannot be accessed.',
    unavailable: 'Unavailable',
    effectivePending: 'Pending',
    effectiveActive: 'Active',
    effectiveExpired: 'Expired',
    effectiveRevoked: 'Revoked',
  },
} as const

export const diagnosticsCopy = {
  ar: {
    inspector: 'مفتش قرارات الوصول',
    inspectorIntro: 'أدخل معرّف القرار لعرض شرحه الكامل.',
    technicalNotice:
      'شاشة تشخيص تقنية مخصصة للمسؤولين — استثناء موثّق من قاعدة «مصطلح المستخدم لا مصطلح المعماري» (قانون التصميم 2.5).',
    decisionId: 'معرّف القرار',
    inspect: 'فحص',
    inspecting: 'جارٍ الفحص…',
    idle: 'أدخل معرّف قرار لعرض شرحه.',
    allow: 'مسموح',
    deny: 'مرفوض',
    action: 'الإجراء',
    resourceType: 'نوع المورد',
    resourceId: 'معرّف المورد',
    policyVersion: 'نسخة السياسة',
    factsVersion: 'نسخة الحقائق',
    evaluatedAt: 'وقت التقييم',
    decisionIdLabel: 'معرّف القرار',
    plainLanguage: 'الشرح المبسّط',
    reasonCodes: 'أكواد السبب',
    obligations: 'الالتزامات',
    assignments: 'التعيينات',
    policies: 'مراجع السياسات',
    justificationTimeline: 'سلسلة التبرير',
    noneRecorded: 'لا شيء مسجّل.',
    notFound: 'لم يُعثر على القرار.',
    error: 'تعذّر فحص القرار.',
    denied: 'لا يمكن الوصول إلى هذا المحتوى.',
    retry: 'إعادة المحاولة',
  },
  en: {
    inspector: 'Access decision inspector',
    inspectorIntro: 'Enter a decision ID to see its full explanation.',
    technicalNotice:
      'A technical diagnostic screen for administrators — the documented exception to the "user terms, not architect terms" rule (DESIGN-RULES §2.5).',
    decisionId: 'Decision ID',
    inspect: 'Inspect',
    inspecting: 'Inspecting…',
    idle: 'Enter a decision ID to see its explanation.',
    allow: 'Allow',
    deny: 'Deny',
    action: 'Action',
    resourceType: 'Resource type',
    resourceId: 'Resource ID',
    policyVersion: 'Policy version',
    factsVersion: 'Facts version',
    evaluatedAt: 'Evaluated at',
    decisionIdLabel: 'Decision ID',
    plainLanguage: 'Plain-language explanation',
    reasonCodes: 'Reason codes',
    obligations: 'Obligations',
    assignments: 'Assignments',
    policies: 'Policy references',
    justificationTimeline: 'Justification chain',
    noneRecorded: 'None recorded.',
    notFound: 'Decision not found.',
    error: 'Could not inspect the decision.',
    denied: 'This content cannot be accessed.',
    retry: 'Try again',
  },
} as const

export const bootstrapCopy = {
  ar: {
    title: 'التهيئة الأولية',
    intro:
      'يؤسّس هذا الإجراء أول مالك للنظام عند تركيب جديد. يُنفَّذ مرة واحدة في عمر النظام.',
    pendingStatus: 'بانتظار الاكتمال',
    expiresAt: 'تنتهي المهلة في',
    reason: 'سبب الإكمال',
    reasonHint: 'سبب تدقيقي إلزامي. يُحفظ في سجل التدقيق.',
    reasonRequired: 'السبب مطلوب.',
    reasonTooLong: 'السبب يجب ألا يتجاوز ٥٠٠ حرف.',
    complete: 'إكمال التهيئة',
    completing: 'جارٍ الإكمال…',
    confirmTitle: 'إكمال التهيئة الأولية',
    confirmBody:
      'سيُغلق هذا الإجراء نافذة التهيئة نهائياً ولا يمكن التراجع عنه. هل تريد المتابعة؟',
    confirm: 'تأكيد',
    cancel: 'إلغاء',
    versionMissing:
      'تعذّر قراءة نسخة الحالة. حدّث الصفحة وحاول مجدداً.',
    saved: 'اكتملت التهيئة.',
  },
  en: {
    title: 'Initial bootstrap',
    intro:
      'This establishes the first system owner on a fresh install. It runs once in the lifetime of the system.',
    pendingStatus: 'Awaiting completion',
    expiresAt: 'Expires at',
    reason: 'Completion reason',
    reasonHint: 'A mandatory audited reason. Stored in the audit trail.',
    reasonRequired: 'A reason is required.',
    reasonTooLong: 'The reason must not exceed 500 characters.',
    complete: 'Complete bootstrap',
    completing: 'Completing…',
    confirmTitle: 'Complete the initial bootstrap',
    confirmBody:
      'This permanently closes the bootstrap window and cannot be undone. Continue?',
    confirm: 'Confirm',
    cancel: 'Cancel',
    versionMissing:
      'The state version could not be read. Refresh the page and try again.',
    saved: 'Bootstrap completed.',
  },
} as const
