export const accountsCopy = {
  ar: {
    title: 'الحسابات والصلاحيات',
    intro: 'أدر حسابات الدخول والأدوار وافحص قرارات الوصول.',
    tabsLabel: 'مساحات الحسابات والصلاحيات',
    tabAccounts: 'الحسابات',
    tabRoles: 'الأدوار',
    tabInspector: 'مفتش القرارات',
    unavailable: 'غير متاح',
    unavailableBody: 'لا تملك الصلاحية المطلوبة لعرض هذا القسم.',
    retry: 'إعادة المحاولة',
    loading: 'جارٍ التحميل…',
    close: 'إغلاق',
    save: 'حفظ',
    cancel: 'إلغاء',
    done: 'تم تنفيذ الإجراء.',
    saveError: 'لم يُحفظ التغيير. أعد المحاولة.',
    stale: 'تغيّرت البيانات من مكان آخر. حدّث القائمة وأعد المحاولة.',
  },
  en: {
    title: 'Accounts & Permissions',
    intro: 'Manage sign-in accounts, roles, and inspect access decisions.',
    tabsLabel: 'Accounts & permissions workspaces',
    tabAccounts: 'Accounts',
    tabRoles: 'Roles',
    tabInspector: 'Decision inspector',
    unavailable: 'Unavailable',
    unavailableBody:
      'You do not have the required permission to view this section.',
    retry: 'Retry',
    loading: 'Loading…',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    done: 'Action completed.',
    saveError: 'The change was not saved. Try again.',
    stale: 'This data changed elsewhere. Refresh the list and try again.',
  },
} as const

export const accountCopy = {
  ar: {
    accounts: 'حسابات الدخول',
    noAccounts: 'لا توجد حسابات دخول بعد.',
    noAccountsBody: 'ابدأ بإنشاء حساب لموظف حتى يتمكن من تسجيل الدخول.',
    employee: 'الموظف',
    username: 'اسم الدخول',
    status: 'الحالة',
    manage: 'إدارة',
    manageAccount: 'إدارة الحساب',
    addAccount: 'إضافة حساب',
    addAccountTitle: 'إضافة حساب دخول',
    addAccountIntro:
      'اختر الموظف واكتب اسم الدخول. يُنشأ الحساب بانتظار التفعيل.',
    create: 'إنشاء الحساب',
    saving: 'جارٍ الحفظ…',
    usernameHint: '٣ أحرف فأكثر: حروف إنجليزية وأرقام و . _ - فقط.',
    validation: 'اختر موظفاً واكتب اسم دخول صحيحاً.',
    peopleError: 'تعذّر تحميل قائمة الموظفين.',
    reason: 'سبب الإجراء (اختياري)',
    reasonHint: 'يُحفظ في سجل التدقيق ليُعرف لاحقاً سبب التغيير.',
    pending: 'بانتظار التفعيل',
    active: 'نشط',
    locked: 'مقفل',
    disabled: 'معطَّل',
    archived: 'مؤرشف',
    mustChangePassword: 'مطلوب من الموظف تغيير كلمة المرور عند الدخول القادم.',
    activate: 'تفعيل الحساب',
    unlock: 'فك القفل',
    disable: 'تعطيل الحساب',
    archive: 'أرشفة الحساب',
    revokeSessions: 'إنهاء الجلسات المفتوحة',
    forcePasswordChange: 'إلزامه بتغيير كلمة المرور',
    noActions: 'لا توجد إجراءات متاحة على هذا الحساب.',
    activateHint: 'يعيد للموظف القدرة على تسجيل الدخول.',
    unlockHint: 'يلغي القفل الناتج عن محاولات الدخول الفاشلة.',
    disableHint: 'يمنع الدخول مؤقتاً مع الاحتفاظ بالحساب.',
    archiveHint: 'إغلاق نهائي للحساب. لا يمكن التراجع.',
    revokeSessionsHint: 'يخرج الموظف من كل الأجهزة فوراً.',
    forcePasswordChangeHint: 'يطلب منه كلمة مرور جديدة عند الدخول القادم.',
    accountsError: 'تعذّر تحميل الحسابات.',
    saveError: 'لم يُحفظ التغيير. أعد المحاولة.',
    peopleLoading: 'جارٍ تحميل الموظفين…',
  },
  en: {
    accounts: 'Sign-in accounts',
    noAccounts: 'No sign-in accounts yet.',
    noAccountsBody: 'Start by creating an account so an employee can sign in.',
    employee: 'Employee',
    username: 'Username',
    status: 'Status',
    manage: 'Manage',
    manageAccount: 'Manage account',
    addAccount: 'Add account',
    addAccountTitle: 'Add a sign-in account',
    addAccountIntro:
      'Pick the employee and choose a username. The account starts as awaiting activation.',
    create: 'Create account',
    saving: 'Saving…',
    usernameHint: 'At least 3 characters: letters, digits, and . _ - only.',
    validation: 'Select an employee and enter a valid username.',
    peopleError: 'Could not load the employee list.',
    reason: 'Reason (optional)',
    reasonHint:
      'Stored in the audit trail so the change can be explained later.',
    pending: 'Awaiting activation',
    active: 'Active',
    locked: 'Locked',
    disabled: 'Disabled',
    archived: 'Archived',
    mustChangePassword: 'The employee must set a new password at next sign-in.',
    activate: 'Activate account',
    unlock: 'Unlock',
    disable: 'Disable account',
    archive: 'Archive account',
    revokeSessions: 'End open sessions',
    forcePasswordChange: 'Require a password change',
    noActions: 'No actions are available on this account.',
    activateHint: 'Restores the employee’s ability to sign in.',
    unlockHint: 'Clears the lock caused by failed sign-in attempts.',
    disableHint: 'Blocks sign-in temporarily while keeping the account.',
    archiveHint: 'Closes the account for good. This cannot be undone.',
    revokeSessionsHint: 'Signs the employee out of every device immediately.',
    forcePasswordChangeHint: 'Asks for a new password at their next sign-in.',
    accountsError: 'Accounts could not be loaded.',
    saveError: 'The change was not saved. Try again.',
    peopleLoading: 'Loading employees…',
  },
} as const

export const roleCopy = {
  ar: {
    roles: 'الأدوار والصلاحيات',
    code: 'رمز الدور',
    name: 'اسم الدور',
    capabilities: 'الصلاحيات',
    create: 'إنشاء دور',
    save: 'حفظ التغييرات',
    edit: 'تعديل',
    archive: 'أرشفة',
    clone: 'نسخ كدور مخصص',
    revoke: 'إزالة',
    cancel: 'إلغاء',
    empty: 'لا توجد أدوار لعرضها.',
    noCatalog:
      'لا تتوفر قائمة الصلاحيات (تحتاج authorization.capability.read).',
    roleError: 'تعذّر حفظ الدور.',
    rolesError: 'تعذّر تحميل الأدوار.',
    countCapabilities: 'صلاحية',
    systemRole: 'نظامي',
    customRole: 'مخصص',
  },
  en: {
    roles: 'Roles & Permissions',
    code: 'Role code',
    name: 'Role name',
    capabilities: 'Capabilities',
    create: 'Create role',
    save: 'Save changes',
    edit: 'Edit',
    archive: 'Archive',
    clone: 'Clone as custom role',
    revoke: 'Remove',
    cancel: 'Cancel',
    empty: 'No roles to display.',
    noCatalog:
      'Capability catalog unavailable (needs authorization.capability.read).',
    roleError: 'Could not save the role.',
    rolesError: 'Roles could not be loaded.',
    countCapabilities: 'capabilities',
    systemRole: 'System',
    customRole: 'Custom',
  },
} as const

export const inspectorCopy = {
  ar: {
    inspector: 'مفتش قرارات الوصول',
    inspectorIntro: 'أدخل معرّف القرار لعرض شرحه الكامل.',
    decisionId: 'معرّف القرار',
    inspect: 'فحص',
    inspecting: 'جارٍ الفحص…',
    idle: 'أدخل معرّف قرار لعرض شرحه.',
    allow: 'مسموح',
    deny: 'مرفوض',
    action: 'الإجراء',
    resourceType: 'نوع المورد',
    resourceId: 'معرّف المورد',
    policyVersion: 'نسخة السياسة',
    factsVersion: 'نسخة الحقائق',
    evaluatedAt: 'وقت التقييم',
    decisionIdLabel: 'معرّف القرار',
    plainLanguage: 'الشرح المبسّط',
    reasonCodes: 'أكواد السبب',
    obligations: 'الالتزامات',
    assignments: 'التعيينات',
    policies: 'مراجع السياسات',
    notFound: 'لم يُعثر على القرار.',
    error: 'تعذّر فحص القرار.',
  },
  en: {
    inspector: 'Access decision inspector',
    inspectorIntro: 'Enter a decision ID to see its full explanation.',
    decisionId: 'Decision ID',
    inspect: 'Inspect',
    inspecting: 'Inspecting…',
    idle: 'Enter a decision ID to see its explanation.',
    allow: 'Allow',
    deny: 'Deny',
    action: 'Action',
    resourceType: 'Resource type',
    resourceId: 'Resource ID',
    policyVersion: 'Policy version',
    factsVersion: 'Facts version',
    evaluatedAt: 'Evaluated at',
    decisionIdLabel: 'Decision ID',
    plainLanguage: 'Plain-language explanation',
    reasonCodes: 'Reason codes',
    obligations: 'Obligations',
    assignments: 'Assignments',
    policies: 'Policy references',
    notFound: 'Decision not found.',
    error: 'Could not inspect the decision.',
  },
} as const
