export const meCopy = {
  ar: {
    title: 'حسابي',
    intro: 'أمانك الشخصي ونطاقات عملك وصلاحياتك في مكان واحد.',
    tabsLabel: 'مساحات حسابي',
    tabSecurity: 'أماني',
    tabAccess: 'صلاحياتي ونطاقاتي',
  },
  en: {
    title: 'My Account',
    intro: 'Your personal security, work scopes, and capabilities in one place.',
    tabsLabel: 'My account workspaces',
    tabSecurity: 'Security',
    tabAccess: 'Scopes & capabilities',
  },
} as const

export const securityCopy = {
  ar: {
    panel: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    lengthHint: '14 حرفاً على الأقل. اختر عبارة يسهل تذكّرها ويصعب تخمينها.',
    confirmHint: 'أعد كتابة كلمة المرور الجديدة نفسها.',
    submit: 'حفظ كلمة المرور',
    saving: 'جارٍ الحفظ…',
    tooShort: 'كلمة المرور الجديدة قصيرة جداً. اكتب 14 حرفاً على الأقل.',
    mismatch: 'الكلمتان غير متطابقتين. تحقّق من التأكيد.',
    failed: 'تعذّر تغيير كلمة المرور. تأكّد من كلمة المرور الحالية ثم أعد المحاولة.',
    success: 'تم تغيير كلمة المرور بنجاح.',
    strength: 'قوة كلمة المرور',
    strengthEmpty: 'اكتب كلمة مرور لمعاينة قوتها',
    weak: 'ضعيفة',
    fair: 'متوسطة',
    strong: 'قوية',
    veryStrong: 'قوية جداً',
  },
  en: {
    panel: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    lengthHint: `At least ${14} characters. Pick a phrase that is easy to recall and hard to guess.`,
    confirmHint: 'Type the same new password again.',
    submit: 'Save password',
    saving: 'Saving…',
    tooShort: `The new password is too short — use at least ${14} characters.`,
    mismatch: 'The two entries do not match. Check the confirmation.',
    failed: 'The password could not be changed. Check your current password and try again.',
    success: 'Password changed successfully.',
    strength: 'Password strength',
    strengthEmpty: 'Type a password to preview its strength',
    weak: 'Weak',
    fair: 'Fair',
    strong: 'Strong',
    veryStrong: 'Very strong',
  },
} as const

export const accessCopy = {
  ar: {
    scopes: 'نطاقاتي',
    scopesHint: 'النطاق الذي تعمل ضمنه حالياً. يتغيّر ما تراه وما تستطيع فعله مع النطاق.',
    effective: 'النطاق الفعّال',
    switching: 'جارٍ تبديل النطاق…',
    scopeError: 'تعذّر تبديل النطاق. أعد المحاولة.',
    noScopes: 'لا توجد نطاقات متاحة.',
    capabilities: 'قدراتي',
    capabilitiesHint: 'الصلاحيات المتاحة لك حالياً، مجمّعة حسب الوحدة. الخادم وحده من يقرر.',
    noCapabilities: 'لا توجد صلاحيات متاحة.',
    retry: 'إعادة المحاولة',
    loading: 'جارٍ تحميل سياق الوصول…',
    denied: 'لا يمكن الوصول إلى هذا المحتوى.',
  },
  en: {
    scopes: 'My scopes',
    scopesHint: 'The scope you are working in right now. What you see and can do changes with the scope.',
    effective: 'Current scope',
    switching: 'Switching scope…',
    scopeError: 'Could not switch the scope. Try again.',
    noScopes: 'No scopes available.',
    capabilities: 'My capabilities',
    capabilitiesHint: 'The capabilities available to you now, grouped by module. Only the server decides.',
    noCapabilities: 'No capabilities available.',
    retry: 'Retry',
    loading: 'Loading access context…',
    denied: 'This content cannot be accessed.',
  },
} as const
