export const documentsCopy = {
  ar: {
    pageTitle: 'المستندات',
    pageDescription: 'مستندات التجمع الصحي وتصنيفاتها',
    back: 'عودة إلى المستندات',
    loading: 'جارٍ تحميل المستندات…',
    retry: 'إعادة المحاولة',
    classificationLabel: 'التصنيف',
    classificationAll: 'كل التصنيفات',
    classificationPublic: 'عام',
    classificationInternal: 'داخلي',
    classificationConfidential: 'سري',
    classificationTopSecret: 'سري للغاية',
    state: 'الحالة',
    retentionUntil: 'الاحتفاظ حتى',
    updatedAt: 'آخر تعديل',
    emptyTitle: 'لا توجد مستندات',
    emptyBody: 'أنشئ مستنداً جديداً أو غيّر عامل التصفية.',
    error: 'تعذر تحميل المستندات. يرجى إعادة المحاولة.',
    forbidden: 'غير مصرح لك بعرض المستندات.',
    open: 'فتح المستند',
    searchLabel: 'بحث',
    searchPlaceholder: 'ابحث في العنوان…',
    createTitle: 'أنشئ مستنداً',
    createTitleLabel: 'العنوان',
    createTitlePlaceholder: 'عنوان المستند…',
    ownerLabel: 'الوحدة المالكة',
    ownerHelp: 'تُستخدم الوحدة الحالية من سياق الوصول.',
    ownerMissing: 'لا توجد وحدة تابعة لمنشأة في سياق الوصول الحالي، لا يمكن إنشاء مستند.',
    restrictionPolicyLabel: 'سياسة التقييد',
    restrictionPolicyHelp: 'مفتاح سياسة التقييد المطبقة على المستند.',
    create: 'أنشئ المستند',
    creating: 'جارٍ الإنشاء…',
    titleRequired: 'عنوان المستند مطلوب.',
    createError: 'تعذر إنشاء المستند. يرجى إعادة المحاولة.',
    metadataTitle: 'بيانات المستند',
    name: 'الاسم',
    description: 'الوصف',
    noDescription: 'لا يوجد وصف',
    createdAt: 'تاريخ الإنشاء',
    versionsTitle: 'النسخ',
    noVersions: 'لا توجد نسخ',
    versionNumber: 'الإصدار',
    fileName: 'اسم الملف',
    linksTitle: 'الروابط',
    noLinks: 'لا توجد روابط',
    relationType: 'نوع العلاقة',
    sourceRecord: 'السجل المصدر',
    accessTitle: 'الوصول',
    accessGrantTitle: 'منح وصول',
    grantTypeLabel: 'نوع الوصول',
    grantTypePreview: 'معاينة',
    grantTypeDownload: 'تنزيل',
    grantVersionLabel: 'النسخة',
    grantPurposeLabel: 'الغرض',
    grantPurposePlaceholder: 'سبب منح الوصول (اختياري)',
    grantVersionRequired: 'اختر نسخة لمنح الوصول.',
    grantCreated: 'مُنح الوصول.',
    actionsTitle: 'الإجراءات المتاحة',
    actionArchive: 'أرشفة',
    actionUnarchive: 'إلغاء الأرشفة',
    actionPlaceHold: 'وضع قيد الحجز',
    actionReleaseHold: 'رفع الحجز',
    actionLink: 'ربط مستند',
    actionUpload: 'رفع إصدار جديد',
    noActions: 'لا توجد إجراءات متاحة حالياً',
    reasonTitle: 'سبب الإجراء',
    reasonLabel: 'السبب',
    reasonPlaceholder: 'اذكر سبباً واضحاً…',
    reasonRequired: 'السبب مطلوب.',
    stale: 'تعارض في الإصدار: تم تحديث المستند من جهة أخرى، تم إعادة تحميله.',
    actionError: 'تعذر تنفيذ الإجراء. يرجى إعادة المحاولة.',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    linkTitle: 'ربط سجل مصدر',
    linkRelationLabel: 'نوع العلاقة',
    linkRelationAttachment: 'مرفق',
    linkRelationEvidence: 'دليل',
    linkRecordIdLabel: 'معرّف السجل المصدر',
    linkRecordIdPlaceholder: 'معرّف UUID للسجل المرتبط',
    linkModuleLabel: 'الوحدة المصدر',
    linkModulePlaceholder: 'مثال: tasks',
    linkRecordTypeLabel: 'نوع السجل',
    linkRecordTypePlaceholder: 'مثال: task',
    recordIdRequired: 'معرّف السجل المصدر مطلوب.',
    uploadTitle: 'رفع إصدار جديد',
    uploadFileLabel: 'الملف',
    uploadIdle: 'اختر ملفاً لرفعه كإصدار جديد.',
    uploadHashing: 'جارٍ حساب بصمة الملف…',
    uploadInitiating: 'جارٍ تجهيز الرفع…',
    uploadUploading: 'جارٍ نقل الملف إلى التخزين…',
    uploadChecking: 'جارٍ التحقق من حالة الرفع…',
    uploadCompleting: 'جارٍ إكمال الرفع…',
    uploadDone: 'تم رفع الإصدار بنجاح.',
    uploadError: 'تعذر رفع الملف. يرجى إعادة المحاولة.',
    uploadRejected: 'رُفض الإصدار بعد الفحص.',
    chooseFile: 'اختيار ملف',
    uploadNow: 'رفع',
    download: 'تنزيل',
    previewTab: 'المعاينة',
    versionsTab: 'النسخ',
    linksTab: 'الروابط',
    accessTab: 'الوصول',
    scanAvailable: 'متاح',
    scanScanning: 'جارٍ الفحص',
    scanRejected: 'مرفوض بعد الفحص',
    scanError: 'تعذر الفحص',
    scanRestricted: 'مقيّد',
  },
  en: {
    pageTitle: 'Documents',
    pageDescription: 'Health cluster documents and their classifications',
    back: 'Back to documents',
    loading: 'Loading documents…',
    retry: 'Retry',
    classificationLabel: 'Classification',
    classificationAll: 'All classifications',
    classificationPublic: 'Public',
    classificationInternal: 'Internal',
    classificationConfidential: 'Confidential',
    classificationTopSecret: 'Top secret',
    state: 'State',
    retentionUntil: 'Retention until',
    updatedAt: 'Last updated',
    emptyTitle: 'No documents',
    emptyBody: 'Create a new document or adjust the filter.',
    error: 'Could not load documents. Please try again.',
    forbidden: 'You are not authorized to view documents.',
    open: 'Open document',
    searchLabel: 'Search',
    searchPlaceholder: 'Search by title…',
    createTitle: 'Create a document',
    createTitleLabel: 'Title',
    createTitlePlaceholder: 'Document title…',
    ownerLabel: 'Owner organization unit',
    ownerHelp: 'Uses the current unit from the access context.',
    ownerMissing: 'No facility-scoped unit in the current access context; documents cannot be created.',
    restrictionPolicyLabel: 'Restriction policy',
    restrictionPolicyHelp: 'Restriction policy key applied to the document.',
    create: 'Create document',
    creating: 'Creating…',
    titleRequired: 'A document title is required.',
    createError: 'Could not create the document. Please try again.',
    metadataTitle: 'Document metadata',
    name: 'Name',
    description: 'Description',
    noDescription: 'No description',
    createdAt: 'Created at',
    versionsTitle: 'Versions',
    noVersions: 'No versions',
    versionNumber: 'Version',
    fileName: 'File name',
    linksTitle: 'Links',
    noLinks: 'No links',
    relationType: 'Relation type',
    sourceRecord: 'Source record',
    accessTitle: 'Access',
    accessGrantTitle: 'Grant access',
    grantTypeLabel: 'Access type',
    grantTypePreview: 'Preview',
    grantTypeDownload: 'Download',
    grantVersionLabel: 'Version',
    grantPurposeLabel: 'Purpose',
    grantPurposePlaceholder: 'Reason for granting access (optional)',
    grantVersionRequired: 'Choose a version to grant access to.',
    grantCreated: 'Access granted.',
    actionsTitle: 'Available actions',
    actionArchive: 'Archive',
    actionUnarchive: 'Unarchive',
    actionPlaceHold: 'Place on hold',
    actionReleaseHold: 'Release hold',
    actionLink: 'Link document',
    actionUpload: 'Upload new version',
    noActions: 'No actions are currently available',
    reasonTitle: 'Action reason',
    reasonLabel: 'Reason',
    reasonPlaceholder: 'Provide a clear reason…',
    reasonRequired: 'A reason is required.',
    stale: 'Version conflict: the document was updated elsewhere, it has been reloaded.',
    actionError: 'Could not perform the action. Please try again.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    linkTitle: 'Link a source record',
    linkRelationLabel: 'Relation type',
    linkRelationAttachment: 'Attachment',
    linkRelationEvidence: 'Evidence',
    linkRecordIdLabel: 'Source record id',
    linkRecordIdPlaceholder: 'UUID of the linked record',
    linkModuleLabel: 'Source module',
    linkModulePlaceholder: 'e.g. tasks',
    linkRecordTypeLabel: 'Record type',
    linkRecordTypePlaceholder: 'e.g. task',
    recordIdRequired: 'A source record id is required.',
    uploadTitle: 'Upload a new version',
    uploadFileLabel: 'File',
    uploadIdle: 'Pick a file to upload as a new version.',
    uploadHashing: 'Hashing the file…',
    uploadInitiating: 'Preparing the upload…',
    uploadUploading: 'Transferring the file to storage…',
    uploadChecking: 'Checking upload status…',
    uploadCompleting: 'Completing the upload…',
    uploadDone: 'Version uploaded successfully.',
    uploadError: 'Could not upload the file. Please try again.',
    uploadRejected: 'The version was rejected after scanning.',
    chooseFile: 'Choose file',
    uploadNow: 'Upload',
    download: 'Download',
    previewTab: 'Preview',
    versionsTab: 'Versions',
    linksTab: 'Links',
    accessTab: 'Access',
    scanAvailable: 'Available',
    scanScanning: 'Scanning',
    scanRejected: 'Rejected after scan',
    scanError: 'Scan failed',
    scanRestricted: 'Restricted',
  },
} as const
