export const documentsCopy = {
  ar: {
    pageTitle: 'المستندات',
    pageDescription: 'مستندات التجمع الصحي وتصنيفاتها',
    back: 'عودة إلى المستندات',
    loading: 'جارٍ تحميل المستندات…',
    retry: 'إعادة المحاولة',
    classificationLabel: 'التصنيف',
    classificationAll: 'كل التصنيفات',
    classificationPublic: 'عام',
    classificationInternal: 'داخلي',
    classificationConfidential: 'سري',
    classificationTopSecret: 'سري للغاية',
    state: 'الحالة',
    retentionUntil: 'الاحتفاظ حتى',
    updatedAt: 'آخر تعديل',
    emptyTitle: 'لا توجد مستندات',
    emptyBody: 'أنشئ مستنداً جديداً أو غيّر عامل التصفية.',
    error: 'تعذر تحميل المستندات. يرجى إعادة المحاولة.',
    forbidden: 'غير مصرح لك بعرض المستندات.',
    open: 'فتح المستند',
    searchLabel: 'بحث',
    searchPlaceholder: 'ابحث في العنوان…',
    createTitle: 'أنشئ مستنداً',
    createTitleLabel: 'العنوان',
    createTitlePlaceholder: 'عنوان المستند…',
    ownerLabel: 'الوحدة المالكة',
    ownerHelp: 'تُستخدم الوحدة الحالية من سياق الوصول.',
    ownerMissing: 'لا توجد وحدة تابعة لمنشأة في سياق الوصول الحالي، لا يمكن إنشاء مستند.',
    ownerBlockedTitle: 'تعذّر فتح نموذج الإنشاء',
    ownerBlockedBody: 'يقتصر إنشاء المستندات على منشأة ضمن نطاق الوصول الحالي. اختر منشأة من محدد النطاق ثم أعد المحاولة، أو ارجع إلى المستندات.',
    restrictionPolicyLabel: 'سياسة التقييد',
    restrictionPolicyLabelHelp: 'مفتاح سياسة التقييد المطبقة على المستند.',
    restrictionPolicyHelp: 'يحدّد مفتاح السياسة افتراضياً سياسة «مقيّد» للمحتوى الحسّاس، ويمكن تخصيصه لكل مستند.',
    createPageTitle: 'أنشئ مستنداً جديداً',
    createPageDescription: 'يبدأ المستند كمسوّدة في منشأتك الحالية. الملف الأول إلزامي، والعنوان يقترحه النظام من اسم الملف وقابل للتعديل.',
    createPageScopeLabel: 'مكان عملك الحالي',
    create: 'أنشئ المستند',
    creating: 'جارٍ الإنشاء…',
    titleRequired: 'عنوان المستند مطلوب.',
    titleTooLong: 'يجب ألا يتجاوز العنوان 255 حرفاً.',
    restrictionPolicyTooLong: 'يجب ألا يتجاوز مفتاح السياسة 128 حرفاً.',
    createError: 'تعذر إنشاء المستند. يرجى إعادة المحاولة.',
    createConflict: 'تعارض في إنشاء المستند (قد يكون مفتاح السياسة محجوزاً)، يرجى إعادة المحاولة.',
    createForbidden: 'غير مصرح لك بإنشاء المستندات.',
    returnToDocuments: 'العودة إلى المستندات',
    descriptionLabel: 'الوصف',
    descriptionPlaceholder: 'تفاصيل إضافية عن المستند (اختياري)',
    descriptionTooLong: 'يجب ألا يتجاوز الوصف 2000 حرف.',
    fileLabel: 'الملف',
    fileRequired: 'يجب اختيار ملف لرفعه مع المستند.',
    fileEmpty: 'الملف المختار فارغ. اختر ملفاً غير فارغ.',
    fileTooLarge: 'يتجاوز حجم الملف الحدّ المسموح به (1 غيغابايت كحدّ أقصى).',
    fileMaxSize: 'الحدّ الأقصى لحجم الملف: 1 غيغابايت.',
    owningFacilityLabel: 'المنشأة المالكة',
    owningFacilityCurrent: 'المنشأة الحالية',
    owningFacilityPlaceholder: 'اختر منشأة…',
    owningFacilitySwitching: 'جارٍ تبديل المنشأة…',
    owningFacilityNoneTitle: 'لا تتوفر منشأة مالكة',
    owningFacilityNoneBody: 'لا تتوفر حالياً منشأة مرتبطة بحسابك لإنشاء المستندات. تواصل مع فريق العمل في مجموعتك لتحديد منشأة، أو ارجع إلى قائمة المستندات.',
    policyAutomaticTitle: 'الحماية والاحتفاظ تلقائيان',
    policyAutomaticBody: 'يطبّق النظام تلقائياً سياسة الحماية وسياسة الاحتفاظ بناءً على التصنيف الذي اخترته. لا حاجة لإدخال مفاتيح يدوياً.',
    ownershipSectionHeading: 'الملكية والحماية',
    fileSectionHeading: 'النسخة الأولى',
    reviewTitle: 'مراجعة قبل الإنشاء',
    reviewTitleLabel: 'العنوان',
    reviewTitleFallback: 'سيُستخدم اسم الملف كعنوان',
    reviewClassificationLabel: 'التصنيف',
    reviewFacilityLabel: 'المنشأة المالكة',
    reviewFileLabel: 'الملف',
    reviewPolicyLabel: 'السياسة',
    reviewPolicyValue: 'تلقائية من النظام',
    reviewFileSize: 'الحجم',
    fileChosenLabel: 'تم اختيار الملف',
    fileReplaceLabel: 'استبدال الملف',
    submitCreate: 'أنشئ المستند',
    submitting: 'جارٍ رفع المستند…',
    intakeErrorMetadata: 'تعذّر تجهيز البيانات للرفع. يرجى المراجعة والمحاولة مجدداً.',
    intakeErrorAuth: 'غير مصرح لك بإنشاء المستندات في هذه المنشأة.',
    intakeErrorConflict: 'تعارض أثناء تجهيز الرفع. يرجى المراجعة والمحاولة.',
    intakeErrorGeneral: 'تعذّر إنشاء المستند. يرجى إعادة المحاولة.',
    scanRejectedIntake: 'رُفض الملف بعد فحص الأمان. يرجى اختيار ملف آخر.',
    resumeHint: 'استؤنفت محاولة الرفع السابقة دون إنشاء مستند جديد.',
    metadataTitle: 'بيانات المستند',
    name: 'الاسم',
    description: 'الوصف',
    noDescription: 'لا يوجد وصف',
    createdAt: 'تاريخ الإنشاء',
    versionsTitle: 'النسخ',
    noVersions: 'لا توجد نسخ',
    versionNumber: 'الإصدار',
    fileName: 'اسم الملف',
    linksTitle: 'الروابط',
    noLinks: 'لا توجد روابط',
    relationType: 'نوع العلاقة',
    sourceRecord: 'السجل المصدر',
    accessTitle: 'الوصول',
    accessGrantTitle: 'منح وصول',
    grantTypeLabel: 'نوع الوصول',
    grantTypePreview: 'معاينة',
    grantTypeDownload: 'تنزيل',
    grantVersionLabel: 'النسخة',
    grantPurposeLabel: 'الغرض',
    grantPurposePlaceholder: 'سبب منح الوصول (اختياري)',
    grantVersionRequired: 'اختر نسخة لمنح الوصول.',
    grantCreated: 'مُنح الوصول.',
    actionsTitle: 'الإجراءات المتاحة',
    actionArchive: 'أرشفة',
    actionUnarchive: 'إلغاء الأرشفة',
    actionPlaceHold: 'وضع قيد الحجز',
    actionReleaseHold: 'رفع الحجز',
    actionLink: 'ربط مستند',
    actionUpload: 'رفع إصدار جديد',
    noActions: 'لا توجد إجراءات متاحة حالياً',
    reasonTitle: 'سبب الإجراء',
    reasonLabel: 'السبب',
    reasonPlaceholder: 'اذكر سبباً واضحاً…',
    reasonRequired: 'السبب مطلوب.',
    stale: 'تعارض في الإصدار: تم تحديث المستند من جهة أخرى، تم إعادة تحميله.',
    actionError: 'تعذر تنفيذ الإجراء. يرجى إعادة المحاولة.',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    linkTitle: 'ربط سجل مصدر',
    linkRelationLabel: 'نوع العلاقة',
    linkRelationAttachment: 'مرفق',
    linkRelationEvidence: 'دليل',
    linkRecordIdLabel: 'معرّف السجل المصدر',
    linkRecordIdPlaceholder: 'معرّف UUID للسجل المرتبط',
    linkModuleLabel: 'الوحدة المصدر',
    linkModulePlaceholder: 'مثال: tasks',
    linkRecordTypeLabel: 'نوع السجل',
    linkRecordTypePlaceholder: 'مثال: task',
    recordIdRequired: 'معرّف السجل المصدر مطلوب.',
    uploadTitle: 'رفع إصدار جديد',
    uploadPageDescription: 'يرفع ملفًا ليكون إصدارًا جديدًا من المستند، مع فحص أمني تلقائي قبل الاعتماد.',
    uploadFileLabel: 'الملف',
    uploadSectionHeading: 'ملف الإصدار الجديد',
    uploadIdle: 'اختر ملفاً لرفعه كإصدار جديد.',
    uploadHashing: 'جارٍ حساب بصمة الملف…',
    uploadInitiating: 'جارٍ تجهيز الرفع…',
    uploadUploading: 'جارٍ نقل الملف إلى التخزين…',
    uploadChecking: 'جارٍ التحقق من حالة الرفع…',
    uploadCompleting: 'جارٍ إكمال الرفع…',
    uploadDone: 'تم رفع الإصدار بنجاح.',
    uploadError: 'تعذر رفع الملف. يرجى إعادة المحاولة.',
    uploadRejected: 'رُفض الإصدار بعد الفحص.',
    chooseFile: 'اختيار ملف',
    uploadNow: 'رفع',
    download: 'تنزيل',
    previewTab: 'المعاينة',
    versionsTab: 'النسخ',
    linksTab: 'الروابط',
    accessTab: 'الوصول',
    scanAvailable: 'متاح',
    scanScanning: 'جارٍ الفحص',
    scanRejected: 'مرفوض بعد الفحص',
    scanError: 'تعذر الفحص',
    scanRestricted: 'مقيّد',
  },
  en: {
    pageTitle: 'Documents',
    pageDescription: 'Health cluster documents and their classifications',
    back: 'Back to documents',
    loading: 'Loading documents…',
    retry: 'Retry',
    classificationLabel: 'Classification',
    classificationAll: 'All classifications',
    classificationPublic: 'Public',
    classificationInternal: 'Internal',
    classificationConfidential: 'Confidential',
    classificationTopSecret: 'Top secret',
    state: 'State',
    retentionUntil: 'Retention until',
    updatedAt: 'Last updated',
    emptyTitle: 'No documents',
    emptyBody: 'Create a new document or adjust the filter.',
    error: 'Could not load documents. Please try again.',
    forbidden: 'You are not authorized to view documents.',
    open: 'Open document',
    searchLabel: 'Search',
    searchPlaceholder: 'Search by title…',
    createTitle: 'Create a document',
    createTitleLabel: 'Title',
    createTitlePlaceholder: 'Document title…',
    ownerLabel: 'Owner organization unit',
    ownerHelp: 'Uses the current unit from the access context.',
    ownerMissing: 'No facility-scoped unit in the current access context; documents cannot be created.',
    ownerBlockedTitle: 'Cannot open the create form',
    ownerBlockedBody: 'Creating documents is limited to a facility within the current scope. Pick a facility in the scope switcher and try again, or return to documents.',
    restrictionPolicyLabel: 'Restriction policy',
    restrictionPolicyLabelHelp: 'Restriction policy key applied to the document.',
    restrictionPolicyHelp: 'Defaults to the “restricted” policy for sensitive content; can be tailored per document.',
    createPageTitle: 'Create a new document',
    createPageDescription: 'A document starts as a draft in your current facility. The first file is required; the title is pre-filled from the file name and is editable.',
    createPageScopeLabel: 'Your current scope',
    create: 'Create document',
    creating: 'Creating…',
    titleRequired: 'A document title is required.',
    titleTooLong: 'The title must be at most 255 characters.',
    restrictionPolicyTooLong: 'The policy key must be at most 128 characters.',
    createError: 'Could not create the document. Please try again.',
    createConflict: 'Conflict while creating the document (the policy key may already be in use). Please try again.',
    createForbidden: 'You are not authorized to create documents.',
    returnToDocuments: 'Back to documents',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'Additional details about the document (optional)',
    descriptionTooLong: 'The description must be at most 2000 characters.',
    fileLabel: 'File',
    fileRequired: 'A file is required to create the document.',
    fileEmpty: 'The selected file is empty. Choose a non-empty file.',
    fileTooLarge: 'The file exceeds the maximum allowed size (1 GiB).',
    fileMaxSize: 'Maximum file size: 1 GiB.',
    owningFacilityLabel: 'Owning facility',
    owningFacilityCurrent: 'Current facility',
    owningFacilityPlaceholder: 'Pick a facility…',
    owningFacilitySwitching: 'Switching facility…',
    owningFacilityNoneTitle: 'No owning facility available',
    owningFacilityNoneBody: 'No facility is currently linked to your account for creating documents. Reach out to your team to designate one, or return to the document list.',
    policyAutomaticTitle: 'Protection and retention are automatic',
    policyAutomaticBody: 'The system applies the protection policy and retention automatically based on the chosen classification. No manual keys are needed.',
    ownershipSectionHeading: 'Ownership and protection',
    fileSectionHeading: 'First version',
    reviewTitle: 'Review before creating',
    reviewTitleLabel: 'Title',
    reviewTitleFallback: 'Will use the file name as the title',
    reviewClassificationLabel: 'Classification',
    reviewFacilityLabel: 'Owning facility',
    reviewFileLabel: 'File',
    reviewPolicyLabel: 'Policy',
    reviewPolicyValue: 'Applied automatically',
    reviewFileSize: 'Size',
    fileChosenLabel: 'File chosen',
    fileReplaceLabel: 'Replace file',
    submitCreate: 'Create document',
    submitting: 'Uploading document…',
    intakeErrorMetadata: 'Could not prepare the data for upload. Please review and try again.',
    intakeErrorAuth: 'You are not authorized to create documents in this facility.',
    intakeErrorConflict: 'Conflict while preparing the upload. Please review and try again.',
    intakeErrorGeneral: 'Could not create the document. Please try again.',
    scanRejectedIntake: 'The file was rejected after security scanning. Please choose another file.',
    resumeHint: 'Resumed the previous upload attempt without creating a new document.',
    metadataTitle: 'Document metadata',
    name: 'Name',
    description: 'Description',
    noDescription: 'No description',
    createdAt: 'Created at',
    versionsTitle: 'Versions',
    noVersions: 'No versions',
    versionNumber: 'Version',
    fileName: 'File name',
    linksTitle: 'Links',
    noLinks: 'No links',
    relationType: 'Relation type',
    sourceRecord: 'Source record',
    accessTitle: 'Access',
    accessGrantTitle: 'Grant access',
    grantTypeLabel: 'Access type',
    grantTypePreview: 'Preview',
    grantTypeDownload: 'Download',
    grantVersionLabel: 'Version',
    grantPurposeLabel: 'Purpose',
    grantPurposePlaceholder: 'Reason for granting access (optional)',
    grantVersionRequired: 'Choose a version to grant access to.',
    grantCreated: 'Access granted.',
    actionsTitle: 'Available actions',
    actionArchive: 'Archive',
    actionUnarchive: 'Unarchive',
    actionPlaceHold: 'Place on hold',
    actionReleaseHold: 'Release hold',
    actionLink: 'Link document',
    actionUpload: 'Upload new version',
    noActions: 'No actions are currently available',
    reasonTitle: 'Action reason',
    reasonLabel: 'Reason',
    reasonPlaceholder: 'Provide a clear reason…',
    reasonRequired: 'A reason is required.',
    stale: 'Version conflict: the document was updated elsewhere, it has been reloaded.',
    actionError: 'Could not perform the action. Please try again.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    linkTitle: 'Link a source record',
    linkRelationLabel: 'Relation type',
    linkRelationAttachment: 'Attachment',
    linkRelationEvidence: 'Evidence',
    linkRecordIdLabel: 'Source record id',
    linkRecordIdPlaceholder: 'UUID of the linked record',
    linkModuleLabel: 'Source module',
    linkModulePlaceholder: 'e.g. tasks',
    linkRecordTypeLabel: 'Record type',
    linkRecordTypePlaceholder: 'e.g. task',
    recordIdRequired: 'A source record id is required.',
    uploadTitle: 'Upload a new version',
    uploadPageDescription: 'Uploads a file as a new version of the document, with automatic security scanning before acceptance.',
    uploadFileLabel: 'File',
    uploadSectionHeading: 'New version file',
    uploadIdle: 'Pick a file to upload as a new version.',
    uploadHashing: 'Hashing the file…',
    uploadInitiating: 'Preparing the upload…',
    uploadUploading: 'Transferring the file to storage…',
    uploadChecking: 'Checking upload status…',
    uploadCompleting: 'Completing the upload…',
    uploadDone: 'Version uploaded successfully.',
    uploadError: 'Could not upload the file. Please try again.',
    uploadRejected: 'The version was rejected after scanning.',
    chooseFile: 'Choose file',
    uploadNow: 'Upload',
    download: 'Download',
    previewTab: 'Preview',
    versionsTab: 'Versions',
    linksTab: 'Links',
    accessTab: 'Access',
    scanAvailable: 'Available',
    scanScanning: 'Scanning',
    scanRejected: 'Rejected after scan',
    scanError: 'Scan failed',
    scanRestricted: 'Restricted',
  },
} as const
