export const reportsCopy = {
  ar: {
    title: 'التقارير والمراقبة',
    description: 'التقارير ولوحات المؤشرات وسجل التدقيق ضمن نطاقك.',
    tabsLabel: 'مساحة التقارير والمراقبة',
    tabReports: 'التقارير',
    tabDashboards: 'لوحات المؤشرات',
    tabAudit: 'سجل التدقيق',
    tabExports: 'التصديرات',
    // Reports tab
    reportsTitle: 'التقارير',
    reportsDescription: 'التقارير المتاحة ضمن نطاقك. اختر تقريرًا لعرض نتيجته أو تصديرها.',
    failed: 'تعذر تحميل التقارير.',
    empty: 'لا توجد تقارير متاحة ضمن نطاقك.',
    selectReport: 'اختر تقريرًا',
    reportDetail: 'تفاصيل التقرير',
    values: 'القيم',
    status: 'الحالة',
    classification: 'التصنيف',
    version: 'الإصدار',
    updated: 'آخر تحديث',
    export: 'تصدير',
    exportFormat: 'التنسيق',
    exportFormatTitle: 'تصدير التقرير',
    exportFormatHelp: 'اختر صيغة الملف الناتج.',
    createExport: 'إنشاء التصدير',
    cancel: 'إلغاء',
    exportQueued: 'جارٍ تجهيز التصدير…',
    exportFailed: 'تعذر إنشاء التصدير.',
    exportExpired: 'انتهت صلاحية التصدير أو تعذر تحميله.',
    download: 'تنزيل الملف',
    downloadFailed: 'تعذر تنزيل الملف.',
    retry: 'إعادة المحاولة',
    notAvailable: 'غير متاح',
    // Dashboards tab
    dashboardsTitle: 'لوحات المؤشرات',
    dashboardsDescription: 'اللوحات المنشورة والمصرح بها ضمن نطاقك.',
    dashboardsFailed: 'تعذر تحميل لوحات المؤشرات.',
    dashboardsEmpty: 'لا توجد لوحات منشورة ضمن نطاقك.',
    selectDashboard: 'اختر لوحة',
    dashboardDetail: 'تفاصيل اللوحة',
    dashboardChart: 'مؤشرات اللوحة',
    // Exports tab
    exportsTitle: 'التصديرات',
    exportsDescription: 'تصديرات جلسة العمل هذه. تُنزَّل فور الجهوزية.',
    noExports: 'لا توجد تصديرات بعد.',
    noExportsBody: 'أنشئ تصديرًا من التقارير أو سجل التدقيق وسيظهر هنا.',
    preparing: 'قيد التحضير',
    ready: 'جاهز',
    failedShort: 'فشل',
    type: 'النوع',
    format: 'الصيغة',
    created: 'أُنشئ',
    reportType: 'تقرير',
    auditType: 'سجل تدقيق',
  },
  en: {
    title: 'Reports & monitoring',
    description: 'Reports, dashboards, and the audit ledger within your scope.',
    tabsLabel: 'Reports and monitoring workspace',
    tabReports: 'Reports',
    tabDashboards: 'Dashboards',
    tabAudit: 'Audit ledger',
    tabExports: 'Exports',
    // Reports tab
    reportsTitle: 'Reports',
    reportsDescription: 'Reports available in your scope. Select a report to view or export its result.',
    failed: 'Reports could not be loaded.',
    empty: 'No reports are available in your scope.',
    selectReport: 'Select a report',
    reportDetail: 'Report details',
    values: 'Values',
    status: 'Status',
    classification: 'Classification',
    version: 'Version',
    updated: 'Updated',
    export: 'Export',
    exportFormat: 'Format',
    exportFormatTitle: 'Export report',
    exportFormatHelp: 'Choose the format of the resulting file.',
    createExport: 'Create export',
    cancel: 'Cancel',
    exportQueued: 'Preparing export…',
    exportFailed: 'The export could not be created.',
    exportExpired: 'The export expired or could not be downloaded.',
    download: 'Download file',
    downloadFailed: 'The file could not be downloaded.',
    retry: 'Retry',
    notAvailable: 'Not available',
    // Dashboards tab
    dashboardsTitle: 'Dashboards',
    dashboardsDescription: 'Published dashboards authorized within your scope.',
    dashboardsFailed: 'Dashboards could not be loaded.',
    dashboardsEmpty: 'No published dashboards are available in your scope.',
    selectDashboard: 'Select a dashboard',
    dashboardDetail: 'Dashboard details',
    dashboardChart: 'Dashboard metrics',
    // Exports tab
    exportsTitle: 'Exports',
    exportsDescription: 'Exports created during this workspace session. Download once ready.',
    noExports: 'No exports yet.',
    noExportsBody: 'Create an export from Reports or the Audit ledger and it will appear here.',
    preparing: 'Preparing',
    ready: 'Ready',
    failedShort: 'Failed',
    type: 'Type',
    format: 'Format',
    created: 'Created',
    reportType: 'Report',
    auditType: 'Audit export',
  },
} as const
