import { useRef, useState } from 'react'
import { ApiError, type Session } from '../../api'
import { createRequest, createWorkDefinition, createWorkDefinitionVersion, createWorkflowDefinition, publishWorkDefinitionVersion, publishWorkflowVersion, startWorkflow, getWorkflowInstance, createTaskFromStep, submitRequest, completeRequest, transitionTask, type Day2Entity } from '../../api/day2'

type Locale = 'ar' | 'en'
const copy = { ar: { title: 'مسار الطلبات وسير العمل', admin: 'إعداد التعريفات', request: 'إنشاء طلب', code: 'رمز تعريف العمل', name: 'اسم التعريف', source: 'نوع السجل المصدر', save: 'حفظ ونشر', requestTitle: 'عنوان الطلب', description: 'الوصف', submit: 'إنشاء وإرسال الطلب', task: 'المهمة الناتجة', complete: 'إكمال المهمة', returned: 'إعادة المهمة', done: 'اكتمل الإجراء', error: 'تعذر تنفيذ الإجراء. تحقق من الصلاحية أو حدّث الصفحة.', required: 'أكمل الحقول المطلوبة.' }, en: { title: 'Request workflow', admin: 'Definition setup', request: 'Create request', code: 'Work definition code', name: 'Definition name', source: 'Source record type', save: 'Save and publish', requestTitle: 'Request title', description: 'Description', submit: 'Create and submit request', task: 'Generated task', complete: 'Complete task', returned: 'Return task', done: 'Action completed', error: 'The action could not be completed. Check access or refresh.', required: 'Complete the required fields.' } } as const

export function Day2Workflow({ locale, session, onSessionExpired }: { locale: Locale; session: Session; onSessionExpired: () => void }) {
  const t = copy[locale]; const [code, setCode] = useState('request_flow'); const [name, setName] = useState('Request workflow'); const [source, setSource] = useState('work_record'); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [task, setTask] = useState<Day2Entity | null>(null); const [record, setRecord] = useState<Day2Entity | null>(null); const [workflowVersion, setWorkflowVersion] = useState<Day2Entity | null>(null); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const errorRef = useRef<HTMLParagraphElement>(null)
  async function run(action: () => Promise<unknown>, success: string) { setBusy(true); setStatus(''); try { await action(); setStatus(success) } catch (error) { if (error instanceof ApiError && error.status === 401) onSessionExpired(); else { setStatus(t.error); window.requestAnimationFrame(() => errorRef.current?.focus()) } } finally { setBusy(false) } }
  async function setup() { if (!code.trim() || !name.trim() || !source.trim()) { setStatus(t.required); return } await run(async () => { const work = await createWorkDefinition(session.access_token, { code, name, default_classification: 'internal' }); const workVersion = await createWorkDefinitionVersion(session.access_token, String(work.id), { schema_document: { title: 'string', description: 'string' }, field_policy_key: 'default' }); await publishWorkDefinitionVersion(session.access_token, String(workVersion.id), Number(workVersion.lock_version ?? 1)); const flow = await createWorkflowDefinition(session.access_token, { code: `${code}_flow`, name, source_record_type: source }); const published = await publishWorkflowVersion(session.access_token, String(flow.version.id), Number(flow.version.lock_version ?? 1)); setWorkflowVersion(published) }, t.done) }
  async function submit() { if (!title.trim() || !description.trim() || !workflowVersion?.id) { setStatus(!workflowVersion ? t.required : t.required); return } await run(async () => { const request = await createRequest(session.access_token, { work_definition_code: 'request', title, description }); const submitted = await submitRequest(session.access_token, String(request.id), Number(request.lock_version ?? 1)); setRecord(submitted); const instance = await startWorkflow(session.access_token, { workflow_version_id: String(workflowVersion.id), source_module: 'work', record_type: 'request', record_id: String(submitted.id) }); const detail = await getWorkflowInstance(session.access_token, String(instance.id)); const step = detail.steps.find(item => item.status === 'active') ?? detail.steps[0]; if (step?.id) setTask(await createTaskFromStep(session.access_token, String(step.id), title)) }, t.done) }
  return <main className="content-page" aria-labelledby="day2-heading"><h1 id="day2-heading">{t.title}</h1><p ref={errorRef} tabIndex={-1} role="status" aria-live="polite">{status}</p><div className="form-grid"><section className="surface-card"><h2>{t.admin}</h2><label>{t.code}<input value={code} onChange={e => setCode(e.target.value)} /></label><label>{t.name}<input value={name} onChange={e => setName(e.target.value)} /></label><label>{t.source}<input value={source} onChange={e => setSource(e.target.value)} /></label><button className="primary-button" disabled={busy} onClick={() => void setup()}>{t.save}</button></section><section className="surface-card"><h2>{t.request}</h2><label>{t.requestTitle}<input value={title} onChange={e => setTitle(e.target.value)} /></label><label>{t.description}<textarea value={description} onChange={e => setDescription(e.target.value)} /></label><button className="primary-button" disabled={busy} onClick={() => void submit()}>{t.submit}</button>{task && <div role="region" aria-label={t.task}><h2>{t.task}</h2><p>{String(task.title ?? task.id ?? '')}</p><button className="secondary-button" disabled={busy} onClick={() => void run(async () => { const returned = await transitionTask(session.access_token, String(task.id), 'return-completion', Number(task.lock_version ?? 1)); setTask(returned) }, t.done)}>{t.returned}</button><button className="secondary-button" disabled={busy} onClick={() => void run(async () => { const completed = await transitionTask(session.access_token, String(task.id), 'complete', Number(task.lock_version ?? 1)); setTask(completed); if (record) await completeRequest(session.access_token, String(record.id), Number(record.lock_version ?? 1)) }, t.done)}>{t.complete}</button></div>}</section></div></main>
}
