export const notificationsCopy = {
  ar: {
    title: 'الإشعارات',
    description: 'آخر الإشعارات الموجهة إليك في المنصة.',
    noNotifications: 'لا توجد إشعارات',
    noNotificationsBody: 'عندما يصلك شيء جديد سيظهر هنا.',
    markRead: 'تحديد كمقروء',
    marking: 'جارٍ التحديث…',
    loadMore: 'عرض المزيد',
    loadingMore: 'جارٍ التحميل…',
    error: 'حدث خطأ غير متوقع.',
    retry: 'إعادة المحاولة',
    loadMoreFailed: 'تعذر تحميل المزيد من الإشعارات.',
    markFailed: 'تعذر تحديث الإشعار.',
    from: 'من',
    count: 'إشعار',
    unread: 'غير مقروء',
    read: 'مقروء',
  },
  en: {
    title: 'Notifications',
    description: 'Latest notifications addressed to you on the platform.',
    noNotifications: 'No notifications',
    noNotificationsBody: 'New items will appear here when they arrive.',
    markRead: 'Mark as read',
    marking: 'Updating…',
    loadMore: 'Load more',
    loadingMore: 'Loading…',
    error: 'Something went wrong.',
    retry: 'Retry',
    loadMoreFailed: 'Could not load more notifications.',
    markFailed: 'Could not update the notification.',
    from: 'From',
    count: 'notifications',
    unread: 'Unread',
    read: 'Read',
  },
} as const

export type NotificationsCopy = (typeof notificationsCopy)['ar']
