export const tasksCopy = {
  ar: {
    pageTitle: 'المهام',
    back: 'عودة إلى المهام',
    loading: 'جارٍ تحميل المهمة…',
    retry: 'إعادة المحاولة',
    metaTitle: 'تفاصيل المهمة',
    state: 'الحالة',
    priority: 'الأولوية',
    priorityLow: 'منخفضة',
    priorityNormal: 'عادية',
    priorityHigh: 'عالية',
    priorityUrgent: 'عاجلة',
    classification: 'التصنيف',
    classificationPublic: 'عام',
    classificationInternal: 'داخلي',
    classificationConfidential: 'سري',
    classificationTopSecret: 'سري للغاية',
    assignee: 'المسند إليه',
    creator: 'المنشئ',
    dueAt: 'الاستحقاق',
    createdAt: 'تاريخ الإنشاء',
    updatedAt: 'آخر تحديث',
    description: 'الوصف',
    noDescription: 'لا يوجد وصف',
    participants: 'المشاركون',
    noParticipants: 'لا يوجد مشاركون',
    addParticipant: 'إضافة مشارك',
    addParticipantLabel: 'معرّف المستخدم',
    addParticipantPlaceholder: 'معرّف المستخدم المراد إضافته',
    addParticipantRequired: 'معرّف المستخدم مطلوب.',
    attachments: 'المستندات المرفقة',
    noAttachments: 'لا توجد مستندات مرفقة',
    comments: 'التعليقات',
    noComments: 'لا توجد تعليقات',
    actionStart: 'بدء',
    actionBlock: 'حظر',
    actionUnblock: 'رفع الحظر',
    actionComplete: 'إكمال',
    actionCancel: 'إلغاء',
    actionEdit: 'تعديل',
    actionComment: 'إضافة تعليق',
    actionAttach: 'إرفاق مستند',
    noActions: 'لا توجد إجراءات متاحة حالياً',
    dialogBlockTitle: 'حظر المهمة',
    dialogBlockDescription: 'يرجى توضيح سبب الحظر.',
    dialogCancelTitle: 'إلغاء المهمة',
    dialogCancelDescription: 'يرجى توضيح سبب الإلغاء.',
    dialogCompleteTitle: 'إكمال المهمة',
    dialogCompleteDescription: 'أضف ملاحظة حول إنجاز المهمة.',
    dialogReasonLabel: 'السبب',
    dialogReasonPlaceholder: 'اذكر سبباً واضحاً…',
    dialogNoteLabel: 'الملاحظة',
    dialogNotePlaceholder: 'ملاحظة الإكمال…',
    reasonRequired: 'السبب مطلوب.',
    noteRequired: 'الملاحظة مطلوبة.',
    editTitle: 'تعديل المهمة',
    editTitleLabel: 'العنوان',
    editDescriptionLabel: 'الوصف',
    editPriorityLabel: 'الأولوية',
    titleRequired: 'العنوان مطلوب.',
    titleTooLong: 'يجب ألا يتجاوز العنوان 255 حرفاً.',
    descriptionTooLong: 'يجب ألا يتجاوز الوصف 4000 حرف.',
    commentTitle: 'إضافة تعليق',
    commentBodyLabel: 'نص التعليق',
    commentBodyPlaceholder: 'اكتب تعليقك…',
    commentRequired: 'نص التعليق مطلوب.',
    mentionLabel: 'معرّفات المستخدمين المذكورين',
    mentionPlaceholder: 'معرّفات مفصولة بفواصل (اختياري)',
    attachTitle: 'إرفاق مستند',
    attachDocumentIdLabel: 'معرّف المستند',
    attachDocumentIdPlaceholder: 'أدخل معرّف المستند',
    documentIdRequired: 'معرّف المستند مطلوب.',
    confirm: 'تأكيد',
    cancel: 'إلغاء',
    save: 'حفظ',
    stale: 'تعارض في الإصدار: تم تحديث المهمة من جهة أخرى، تم إعادة تحميلها.',
    actionError: 'تعذر تنفيذ الإجراء. يرجى إعادة المحاولة.',
    close: 'إغلاق',
    detailsTab: 'التفاصيل',
    commentsTab: 'التعليقات',
    participantsTab: 'المشاركون',
  },
  en: {
    pageTitle: 'Tasks',
    back: 'Back to tasks',
    loading: 'Loading task…',
    retry: 'Retry',
    metaTitle: 'Task details',
    state: 'State',
    priority: 'Priority',
    priorityLow: 'Low',
    priorityNormal: 'Normal',
    priorityHigh: 'High',
    priorityUrgent: 'Urgent',
    classification: 'Classification',
    classificationPublic: 'Public',
    classificationInternal: 'Internal',
    classificationConfidential: 'Confidential',
    classificationTopSecret: 'Top secret',
    assignee: 'Assignee',
    creator: 'Creator',
    dueAt: 'Due at',
    createdAt: 'Created at',
    updatedAt: 'Updated at',
    description: 'Description',
    noDescription: 'No description',
    participants: 'Participants',
    noParticipants: 'No participants',
    addParticipant: 'Add participant',
    addParticipantLabel: 'User id',
    addParticipantPlaceholder: 'User id to add',
    addParticipantRequired: 'A user id is required.',
    attachments: 'Attached documents',
    noAttachments: 'No attached documents',
    comments: 'Comments',
    noComments: 'No comments',
    actionStart: 'Start',
    actionBlock: 'Block',
    actionUnblock: 'Unblock',
    actionComplete: 'Complete',
    actionCancel: 'Cancel',
    actionEdit: 'Edit',
    actionComment: 'Add comment',
    actionAttach: 'Attach document',
    noActions: 'No actions are currently available',
    dialogBlockTitle: 'Block task',
    dialogBlockDescription: 'Please explain why the task is blocked.',
    dialogCancelTitle: 'Cancel task',
    dialogCancelDescription: 'Please explain why the task is being cancelled.',
    dialogCompleteTitle: 'Complete task',
    dialogCompleteDescription: 'Add a note about completing the task.',
    dialogReasonLabel: 'Reason',
    dialogReasonPlaceholder: 'Provide a clear reason…',
    dialogNoteLabel: 'Note',
    dialogNotePlaceholder: 'Completion note…',
    reasonRequired: 'A reason is required.',
    noteRequired: 'A note is required.',
    editTitle: 'Edit task',
    editTitleLabel: 'Title',
    editDescriptionLabel: 'Description',
    editPriorityLabel: 'Priority',
    titleRequired: 'A title is required.',
    titleTooLong: 'The title must be at most 255 characters.',
    descriptionTooLong: 'The description must be at most 4000 characters.',
    commentTitle: 'Add comment',
    commentBodyLabel: 'Comment body',
    commentBodyPlaceholder: 'Write your comment…',
    commentRequired: 'A comment body is required.',
    mentionLabel: 'Mentioned user ids',
    mentionPlaceholder: 'Comma-separated ids (optional)',
    attachTitle: 'Attach document',
    attachDocumentIdLabel: 'Document id',
    attachDocumentIdPlaceholder: 'Enter the document id',
    documentIdRequired: 'A document id is required.',
    confirm: 'Confirm',
    cancel: 'Cancel',
    save: 'Save',
    stale: 'Version conflict: the task was updated elsewhere, it has been reloaded.',
    actionError: 'Could not perform the action. Please try again.',
    close: 'Close',
    detailsTab: 'Details',
    commentsTab: 'Comments',
    participantsTab: 'Participants',
  },
} as const
